const $ = (s,root=document)=>root.querySelector(s);
const $$ = (s,root=document)=>[...root.querySelectorAll(s)];

const iconPaths={
 home:'<path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.5V21h14V9.5"/><path d="M9 21v-7h6v7"/>',
 notebook:'<path d="M5 3h12a2 2 0 0 1 2 2v16H7a2 2 0 0 1-2-2V3Z"/><path d="M9 3v18"/><path d="M12 7h4"/><path d="M12 11h4"/>',
 brain:'<path d="M9.5 4.5A3.5 3.5 0 0 0 6 8v1a3 3 0 0 0-1 5.8A3.5 3.5 0 0 0 9 20"/><path d="M14.5 4.5A3.5 3.5 0 0 1 18 8v1a3 3 0 0 1 1 5.8A3.5 3.5 0 0 1 15 20"/><path d="M12 4v16"/><path d="M8 9h4M12 14h4"/>',
 map:'<circle cx="12" cy="5" r="2"/><circle cx="5" cy="18" r="2"/><circle cx="19" cy="18" r="2"/><path d="M12 7v4M12 11 6 16M12 11l6 5"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18"/><path d="m8 15 2 2 5-5"/>',
 spark:'<path d="m12 3 1.3 3.7L17 8l-3.7 1.3L12 13l-1.3-3.7L7 8l3.7-1.3Z"/><path d="m18 14 .8 2.2L21 17l-2.2.8L18 20l-.8-2.2L15 17l2.2-.8Z"/>',
 chat:'<path d="M21 15a4 4 0 0 1-4 4H8l-5 3 1.5-4A8 8 0 1 1 21 15Z"/>',
 pen:'<path d="m4 20 4.5-1 10-10a2.1 2.1 0 0 0-3-3l-10 10Z"/><path d="m13.5 8.5 3 3"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.6v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/>',
 upload:'<path d="M12 16V4M7 9l5-5 5 5"/><path d="M5 13v7h14v-7"/>',
 camera:'<path d="M14.5 5 13 3h-2L9.5 5H5a2 2 0 0 0-2 2v11h18V7a2 2 0 0 0-2-2Z"/><circle cx="12" cy="12" r="4"/>',
 share:'<circle cx="18" cy="5" r="2"/><circle cx="6" cy="12" r="2"/><circle cx="18" cy="19" r="2"/><path d="m8 11 8-5M8 13l8 5"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 arrow:'<path d="m9 18 6-6-6-6"/>',
 rotate:'<path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/>',
 image:'<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m21 15-5-5L5 20"/>',
 users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>'
};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name]||iconPaths.spark}</svg>`}

const API_BASE='https://rfpkznuntzxfoeeavwwf.supabase.co/functions/v1/wrongbook-ai';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_Nt8ik0KBWLdi8hucG9oDRQ_cnMyQ9Gx';
async function apiCall(path,body){
  const res=await fetch(API_BASE+path,{method:'POST',headers:{'content-type':'application/json','apikey':SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify(body)});
  const data=await res.json().catch(()=>({error:'invalid_response'}));
  if(!res.ok) throw new Error(data.detail||data.error||('HTTP '+res.status));
  return data;
}
async function imageFileToData(file,maxSide=1600,quality=.82){
  const url=URL.createObjectURL(file); const img=new Image(); img.src=url; await img.decode();
  let w=img.naturalWidth,h=img.naturalHeight,scale=Math.min(1,maxSide/Math.max(w,h)); w=Math.round(w*scale); h=Math.round(h*scale);
  const c=document.createElement('canvas'); c.width=w;c.height=h; const x=c.getContext('2d'); x.drawImage(img,0,0,w,h); URL.revokeObjectURL(url);
  let dataUrl=c.toDataURL('image/jpeg',quality); return {dataUrl,base64:dataUrl.split(',')[1],mimeType:'image/jpeg'};
}
function ai(){return state.aiAnalysis||null}
function optionLabels(){let a=ai(); return a?.options?.length?a.options.map(o=>String(o.label).toUpperCase()):['A','B','C','D']}
function pct(n){return Math.round((Number(n)||0)*100)+'%'}

const defaultState={
 page:'notebook', studentAnswer:['A','B'], correctAnswer:['A','C'], recognitionConfirmed:false,
 syllabus:{level:'高中',biology:'龍騰',chemistry:'翰林',physics:'龍騰',math:'南一'},
 corrections:{B:'撤去 F₂ 後，摩擦力為 10 N，方向向左。',D:'木塊仍靜止時，合力為 0 N。'},
 savedTruths:['撤去 F₂ 後，靜摩擦力調整為 10 N，方向向左。','物體靜止時，合力必為 0。'],
 hintCount:0, reviewSelections:[], reviewChecked:false, reviewMode:'problem', posts:[], mindAnswers:{},
 userName:'林大同', aiAnalysis:null, uploadImage:'', uploadBase64:'', uploadMime:'image/jpeg', aiLoading:false, aiError:'', tutorResponse:null, aiAnnotations:[]
};
const memStore={};
function storageGet(k){try{return localStorage.getItem(k)}catch(e){return memStore[k]||null}}
function storageSet(k,v){try{localStorage.setItem(k,v)}catch(e){memStore[k]=v}}
let state={...defaultState,...JSON.parse(storageGet('gaidui-state')||'{}')};
function save(){storageSet('gaidui-state',JSON.stringify(state))}
function toast(msg){let t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}

const navItems=[['home','今天'],['notebook','我的錯題'],['concepts','概念地圖'],['mindmap','心智題'],['review','複習計畫'],['community','社群討論'],['settings','課綱設定']];
function shell(){return `<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">錯</div><div><h1>錯題本</h1><small>AI learning prototype</small></div></div><button class="capture-btn" data-action="capture">＋ 掃描新題目</button><nav class="nav">${navItems.map(([p,l])=>`<button class="nav-btn ${state.page===p?'active':''}" data-page="${p}"><span class="nav-icon">${icon(p==='concepts'?'brain':p==='mindmap'?'map':p==='review'?'calendar':p==='community'?'chat':p==='settings'?'settings':p)}</span><span>${l}</span></button>`).join('')}</nav><div class="profile"><div class="profile-row"><div class="avatar">林</div><div><strong>${state.userName}</strong><small>高二 · 龍騰/翰林/南一</small></div></div><div class="streak">連續學習 12 天 🔥</div></div></aside><main class="main"><header class="topbar"><div class="crumb">${crumb()}</div><div class="top-actions"><button class="ghost-btn" data-action="share">${icon('share')} 分享</button><button class="icon-btn" data-page="settings" aria-label="設定">${icon('settings')}</button></div></header><section class="content">${page()}</section></main>${mobileNav()}</div>`}
function crumb(){let name=navItems.find(x=>x[0]===state.page)?.[1]||'';let a=ai();return state.page==='notebook'?(a?`我的錯題 / ${escapeHtml(a.subject||'待分類')} / AI 掃描題目`:'我的錯題 / 物理 / 牛頓運動定律 / 摩擦力'):name}
function mobileNav(){let items=[['home','今天','home'],['notebook','錯題','notebook'],['capture','掃描','camera'],['review','複習','calendar'],['community','社群','chat']];return `<div class="mobile-nav">${items.map(([p,l,i])=>p==='capture'?`<button class="capture-mobile" data-action="capture">${icon(i)}</button>`:`<button class="${state.page===p?'active':''}" data-page="${p}">${icon(i)}<span>${l}</span></button>`).join('')}</div>`}
function page(){switch(state.page){case'home':return homePage();case'concepts':return conceptsPage();case'mindmap':return mindmapPage();case'review':return reviewPage();case'community':return communityPage();case'settings':return settingsPage();default:return notebookPage()}}

function notebookPage(){let a=ai();return `<div class="page-title"><div><h2>${a?'AI 掃描題目':'題目 #PHY-2024-0803-001'}</h2><p>${a?`${escapeHtml(a.subject||'待分類')} · ${escapeHtml(a.questionType||'')} · AI 解析完成，請先確認答案辨識`:'來源：龍騰物理 4上 · 牛頓運動定律 · 錯誤 2 次 · 上次複習 2 天前'}</p></div><div class="ai-status"><span class="ai-dot ${state.aiLoading?'loading':''}"></span>${state.aiLoading?'AI 分析中…':a?'Gemini 已連線':'示範資料'}</div></div>${state.aiError?`<div class="error-box">AI 錯誤：${escapeHtml(state.aiError)}</div>`:''}<div class="workspace-grid"><div class="stack">${problemPanel()}${correctionPanel()}${communityPanel()}</div><div class="stack">${recognitionPanel()}${mappingPanel()}${tutorPanel()}${reviewSchedulePanel()}</div></div>`}
function problemPanel(){let a=ai();let overlays=(state.aiAnnotations||[]).map(x=>`<div class="ai-overlay-note" style="left:${Math.max(2,Math.min(82,Number(x.x)||10))}%;top:${Math.max(2,Math.min(88,Number(x.y)||10))}%">${escapeHtml(x.text||'')}</div>`).join('');if(a&&state.uploadImage){return `<section class="panel"><div class="panel-head"><h3>原始題目 · 直接在題目上寫</h3><div class="meta">原圖永遠保留 · Apple Pencil / 觸控 / 滑鼠</div></div><div class="paper" id="paper"><img class="scan-photo" src="${state.uploadImage}" alt="掃描的原始題目"><div class="scan-text"><strong>AI 辨識文字</strong><br>${escapeHtml(a.problemText||'')}</div>${overlays}<canvas class="canvas-layer" id="drawCanvas"></canvas><div class="paper-toolbar"><div class="toolset"><button class="tool active" data-tool="pen">✎</button><button class="tool" data-tool="eraser">⌫</button><button class="tool" data-action="undoInk">↶</button><button class="tool" data-action="clearInk">清除</button></div><div class="toolset"><button class="tool" data-action="aiOnPaper">✦ AI 在題目上提示</button></div></div></div></section>`}return `<section class="panel"><div class="panel-head"><h3>原始題目 · 直接在題目上寫</h3><div class="meta">Apple Pencil / 滑鼠 / 觸控皆可</div></div><div class="paper" id="paper"><div class="paper-inner"><div class="problem-text">如圖，木塊置於水平桌面上，在水平方向施力 F₁ 與 F₂，木塊保持靜止。已知 F₁ = 10 N，F₂ = 2 N。<br><strong>若撤去 F₂ 後，合力與摩擦力為何？</strong></div><div class="physics-diagram"><div class="ground"></div><div class="block"></div><div class="force f1">F₁ = 10N</div><div class="force f2">F₂ = 2N</div><div class="arrow a1"></div><div class="arrow a2"></div></div><div class="answer-row">我的作答：AB</div><div class="options"><div class="option">A. 合力方向向右</div><div class="option wrong-mark">B. 摩擦力為 8N</div><div class="option">C. 合力為 0N</div><div class="option">D. 摩擦力為 12N</div></div></div><div class="ink-note note1" id="inkNote1">先問：撤掉 F₂ 之後，還有哪些水平力？</div><div class="ink-note note2" id="inkNote2">f = 10 N ←</div><svg class="ai-arrow" id="aiArrow" viewBox="0 0 600 470" preserveAspectRatio="none"><path d="M500 170 C470 160 430 145 390 130"/></svg><canvas class="canvas-layer" id="drawCanvas"></canvas><div class="paper-toolbar"><div class="toolset"><button class="tool active" data-tool="pen">✎</button><button class="tool" data-tool="eraser">⌫</button><button class="tool" data-action="undoInk">↶</button><button class="tool" data-action="clearInk">清除</button></div><div class="toolset"><button class="tool" data-action="aiOnPaper">✦ AI 在題目上提示</button></div></div></div></section>`}
function recognitionPanel(){let a=ai(),labels=optionLabels(),note=a?.recognitionNote||'可以修正 AI 看錯的圈選';return `<section class="panel"><div class="panel-head"><h3>AI 辨識結果</h3><span class="meta">${state.recognitionConfirmed?'已確認':'待你確認'}</span></div><div class="recognition"><div class="recognition-row"><div><strong>辨識你的作答</strong><div class="meta">${escapeHtml(note)}${a?` · 信心 ${pct(a.recognizedAnswerConfidence)}`:''}</div></div><div class="answer-chips">${labels.map(x=>`<button class="chip student ${state.studentAnswer.includes(x)?'on':''}" data-toggle-student="${x}">${x}</button>`).join('')}</div></div><div class="recognition-row"><div><strong>正確答案</strong><div class="meta">${a?`AI 解題信心 ${pct(a.correctAnswerConfidence)}`:'支援複選題'}</div></div><div class="answer-chips">${labels.map(x=>`<button class="chip ${state.correctAnswer.includes(x)?'on':''}" data-toggle-correct="${x}">${x}</button>`).join('')}</div></div></div><div class="callout">AI 目前認為你寫的是 <strong>${state.studentAnswer.join('')||'未作答'}</strong>，正確答案是 <strong>${state.correctAnswer.join('')||'尚未辨識'}</strong>。<strong>你確認後</strong>才會把這筆資料視為真實學習紀錄。</div><div class="two-buttons"><button class="soft-btn" data-action="rescanAI">重新 AI 辨識</button><button class="primary-btn" data-action="confirmRecognition">${state.recognitionConfirmed?'✓ 已確認':'確認正確'}</button></div></section>`}
function mappingPanel(){let a=ai();if(a?.concepts?.length){return `<section class="panel"><div class="panel-head"><h3>概念與課本位置</h3><button class="ghost-btn" data-page="settings">課綱設定</button></div><div class="mapping">${a.concepts.map(c=>`<div style="padding:10px 0;border-bottom:1px solid var(--line)"><div class="concept-path">${escapeHtml(c.nameZh||c.code)} <span class="meta">${escapeHtml(c.code||'')}</span></div><div class="mapping-row"><span class="publisher">${escapeHtml(state.syllabus[subjectKey(a.subject)]||'你的版本')}</span><span>${escapeHtml(c.chapterHint||'需課綱資料庫確認')}</span></div><div class="confidence">AI 概念信心 ${pct(c.confidence)} · 正式版會用課綱 mapping DB 給精確章節</div></div>`).join('')}</div></section>`}return `<section class="panel"><div class="panel-head"><h3>概念與課本位置</h3><button class="ghost-btn" data-page="concepts">查看概念</button></div><div class="mapping"><div class="concept-path">物理 → 牛頓運動定律 → 靜摩擦力</div><div class="mapping-row"><span class="publisher">${state.syllabus.physics}</span><span>4上 · 第 2 章 · 第 1 節</span></div><div class="mapping-row"><span class="publisher">翰林</span><span>4上 · 第 2 章 · 第 2 節</span></div><div class="mapping-row"><span class="publisher">南一</span><span>4上 · 第 2 章 · 第 1 節</span></div></div><div class="weakness"><div class="meter-row"><span>你的掌握度</span><strong>48%</strong><div class="meter"><span style="width:48%"></span></div></div><div class="meta">這個概念已錯 6 次 · 其中 3 次使用提示</div></div></section>`}
function correctionPanel(){let a=ai();if(a?.corrections?.length){return `<section class="panel"><div class="panel-head"><h3>修正敘述 → 記住正確</h3><div class="meta">不是 Q/A flashcard；保留同一敘述並改成真</div></div><div class="correction-panel">${a.corrections.map(c=>`<div class="statement"><div class="status-dot ${c.isCorrect?'good':'bad'}">${c.isCorrect?'✓':escapeHtml(c.label)}</div><div><div class="orig">${escapeHtml(c.label)}. ${escapeHtml(c.original)} ${c.isCorrect?'· 原本正確':'· 原敘述錯誤'}</div><input class="corrected-input" data-correction="${escapeAttr(c.label)}" value="${escapeAttr(state.corrections[c.label]??c.correctedStatement)}"/><div class="truth-label">✓ 修正後的正確敘述 · 記這個</div>${c.whyWrong?`<div class="confidence">為什麼原句錯：${escapeHtml(c.whyWrong)}</div>`:''}</div><button class="soft-btn" data-ai-correct="${escapeAttr(c.label)}" data-statement="${escapeAttr(c.original)}">AI 重改</button></div>`).join('')}</div><div class="two-buttons"><button class="soft-btn" data-action="saveTruths">加入正確敘述庫</button><button class="primary-btn" data-page="review">開始複習</button></div></section>`}let statements=[['A',true,'合力方向向右','合力為 0 N。'],['B',false,'摩擦力為 8 N',state.corrections.B],['C',true,'合力為 0 N','合力為 0 N。'],['D',false,'摩擦力為 12 N',state.corrections.D]];return `<section class="panel"><div class="panel-head"><h3>修正錯誤 → 記住正確</h3><div class="meta">題目保留原樣；記憶材料只存正確版本</div></div><div class="correction-panel">${statements.map(([l,good,orig,corr])=>`<div class="statement"><div class="status-dot ${good?'good':'bad'}">${good?'✓':l}</div><div><div class="orig">${l}. ${orig} ${good?'· 原本正確':'· 請把它改成正確'}</div>${good?`<div>${corr}</div>`:`<input class="corrected-input" data-correction="${l}" value="${escapeAttr(corr)}"/>`}<div class="truth-label">✓ 這是修正後的正確敘述 · 記這個</div></div>${good?'<span class="meta">保留</span>':`<button class="soft-btn" data-ai-correct="${l}">AI 幫我改</button>`}</div>`).join('')}</div><div class="two-buttons"><button class="soft-btn" data-action="saveTruths">加入正確敘述庫</button><button class="primary-btn" data-page="review">開始複習</button></div></section>`}
function tutorPanel(){let a=ai(),tr=state.tutorResponse;return `<section class="panel"><div class="panel-head"><h3>AI 家教 · 在題目上教</h3><span class="meta">${a?'真人掃描題可用':'示範模式'} · 提示 ${state.hintCount} 次</span></div><div class="tutor"><div class="tutor-canvas">${a?`<div class="tutor-step"><div class="step-no">✦</div><div><strong>先問，不直接丟答案。</strong><div>${escapeHtml(a.solutionSummary||'你可以直接問我卡住的步驟。')}</div></div></div>${tr?`<div class="ai-response">${escapeHtml(tr.reply||'')}${tr.nextPrompt?`

下一步：${escapeHtml(tr.nextPrompt)}`:''}</div>`:''}<div class="tutor-input-row"><input id="tutorQuestion" class="tutor-input" placeholder="例如：先不要告訴我答案，提示我下一步"><button class="primary-btn" data-action="askTutor">問 AI</button></div><div class="tutor-actions"><button class="soft-btn" data-action="aiOnPaper">✦ 在原題上提示</button></div>`:`<div class="tutor-step"><div class="step-no">1</div><div><strong>先不要算答案。</strong><div>原本靜止，因此 ΣFₓ = 0。撤去 F₂ 後，先重新畫只剩下的外力。</div></div></div><div class="hand">撤去 F₂ → F₁ = 10N → ，靜摩擦力需調整成 10N ←</div><div class="tutor-step"><div class="step-no">2</div><div>只要仍未超過最大靜摩擦力，木塊依然靜止，所以合力仍為 0。</div></div></div><div class="tutor-actions"><button class="soft-btn" data-action="hint1">提示 1</button><button class="soft-btn" data-action="hint2">畫在題目上</button><button class="primary-btn" data-action="tutorNext">下一步</button></div>`}</div></div></section>`}
function reviewSchedulePanel(){return `<section class="panel"><div class="panel-head"><h3>複習安排</h3><span class="meta">依你的錯誤與提示行為</span></div><div class="mapping"><div style="font-size:12px;color:var(--muted)">下次複習</div><div style="font-size:24px;font-weight:800;margin:4px 0">8/8（週五）</div><div class="meta">先重做原題，再做「正確敘述填空」</div><button class="soft-btn" style="width:100%;margin-top:12px" data-page="review">查看複習計畫</button></div></section>`}
function communityPanel(){return `<section class="panel"><div class="panel-head"><h3>這題的討論</h3><button class="ghost-btn" data-page="community">全部討論</button></div><div class="community"><div class="tabs"><button class="tab active">最有幫助</button><button class="tab">最新</button></div><div class="post"><div class="post-avatar">學</div><div class="post-body"><strong>學長解法分享</strong><p>我一開始也把 8N 當成「新的摩擦力」，但 8N 是原本兩個外力互抵時的摩擦力。撤掉 F₂ 後要重新平衡。</p><div class="post-meta">💡 42 人覺得「這讓我懂了」 · 回覆 8</div></div></div></div></section>`}
