import { chromium } from 'playwright';
import fs from 'node:fs';

const ORIGIN=process.env.WB_LIVE_URL||'https://jamshih.github.io/html/wrongbook-v2/';
const EXPECT=process.env.WB_EXPECT_BUILD||'wrongbook-v5';
const OUT='.qa-artifacts/wrongbook-live';fs.mkdirSync(OUT,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let last='';
for(let i=0;i<60;i++){
  try{const r=await fetch(`${ORIGIN}?deploycheck=${Date.now()}`,{cache:'no-store'});last=await r.text();if(r.ok&&last.includes('name="wrongbook-build"')&&last.includes(EXPECT))break}catch(e){last=String(e)}
  if(i===59)throw new Error(`Pages build marker not ready: ${last.slice(0,500)}`);await sleep(5000);
}
const browser=await chromium.launch({headless:true});let failed=false;
const fail=(tag,detail)=>{failed=true;console.error(tag,JSON.stringify(detail,null,2))};
const results={origin:ORIGIN,build:null,desktop:{},phone:{}};
function watch(page){const errors=[],bad=[],requests=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(`pageerror: ${e.message}`));page.on('response',r=>{if(r.status()>=400&&!r.url().includes('favicon'))bad.push(`${r.status()} ${r.url()}`)});page.on('request',r=>{if(r.url().includes('/functions/v1/wrongbook-'))requests.push({method:r.method(),url:r.url()})});return{errors,bad,requests}}
async function load(page){await page.goto(`${ORIGIN}?liveqa=${Date.now()}`,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForSelector('#app',{timeout:15000});await page.waitForTimeout(700);const build=await page.locator('meta[name="wrongbook-build"]').getAttribute('content');results.build=build;if(!build?.includes(EXPECT))fail('BUILD_MARKER',{build,expect:EXPECT})}
async function openPage(page,name){const desktop=page.locator(`.sidebar [data-page="${name}"]`);if(await desktop.count()&&await desktop.isVisible()){await desktop.click()}else{await page.locator('.mobile-nav [data-action="toggleMenu"]').click();await page.waitForTimeout(80);await page.locator(`.mobile-drawer [data-page="${name}"]`).click()}await page.waitForTimeout(220)}
async function seedFact(page){return page.evaluate(()=>{const p=(state.problems||[]).find(x=>x.subject==='biology')||(state.problems||[])[0];if(!p||typeof v5UpsertGenericFact!=='function')return null;const f=v5UpsertGenericFact({question:'粒線體的主要功能是什麼？',answer:'粒線體是細胞進行有氧呼吸、產生 ATP 的主要場所。',conceptNameZh:'粒線體',confidence:.99,sourceType:'memorization_fact',sourceEvidence:'live QA local-only fixture',standalone:true,dedupeKey:'live-qa-mitochondria'},p);save();return f?.id||null})}
async function desktopQA(){const page=await browser.newPage({viewport:{width:1440,height:900}}),w=watch(page);await load(page);const out={};out.home=(await page.locator('body').innerText()).includes('今天，把錯的真的改會');await openPage(page,'concepts');out.concepts=Boolean(await page.locator('[data-ce-pane="outline"]').count()&&await page.locator('[data-ce-pane="graph"]').count()&&await page.locator('[data-ce-pane="detail"]').count());await page.locator('[data-subject="biology"]').click();await page.waitForTimeout(120);const graph=page.locator('.v5-graph-node');out.biology=await graph.count()>0;if(await graph.count()){await graph.first().click();await page.waitForTimeout(100)}out.synced=await page.locator('.v5-graph-node.is-selected').count()===1&&await page.locator('.v5-concept-detail h2').count()===1;
const factId=await seedFact(page);if(factId){await page.evaluate(id=>{const f=state.genericFacts.find(x=>x.id===id);state.subject='biology';state.page='concepts';state.conceptExplorer=state.conceptExplorer||{};state.conceptExplorer.selectedKey=f?.ownerKey||state.conceptExplorer.selectedKey;save();render()},factId);await page.waitForTimeout(140);const card=page.locator(`[data-fact-id="${factId}"]`);out.factHidden=await card.count()>0&&await card.locator('[data-fact-reveal]').count()>0&&await card.locator('.v5-fact-answer').count()===0;if(await card.locator('[data-fact-reveal]').count()){await card.locator('[data-fact-reveal]').click();await page.waitForTimeout(60)}out.factReveal=await card.locator('.v5-fact-answer').count()>0}else out.factHidden=out.factReveal=false;
await openPage(page,'notebook');const problem=page.locator('[data-problem]').first();if(await problem.count()){await problem.click();await page.waitForTimeout(160)}out.canvas=await page.locator('#drawCanvas').count()>0;out.guideControls=await page.locator('[data-action="guideStart"]').count()>0&&await page.locator('#aiGuideCanvas').count()>0;const before=w.requests.length;if(await page.locator('[data-action="guideStart"]').count()){await page.locator('[data-action="guideStart"]').click();for(let i=0;i<60;i++){await page.waitForTimeout(500);if(w.requests.length>before&&await page.locator('.v5-tutor-stage').count())break}}const tutorReq=w.requests.slice(before).filter(x=>x.url.includes('wrongbook-guide-ai'));out.tutorRequestCount=tutorReq.length;out.tutorStarted=tutorReq.length===1&&await page.locator('.v5-tutor-stage').count()>0;await openPage(page,'mindmap');await page.locator('[data-subject="earth"]').click();await page.waitForTimeout(260);out.earth=await page.evaluate(()=>Boolean(window.v8EarthSourceIntegrity?.().ok))&&await page.locator('[data-strict-page]').count()===2;
const capture=page.locator('[data-action="capture"]').filter({visible:true}).first();if(await capture.count()){await capture.click();await page.waitForTimeout(100)}out.scan=await page.locator('#captureModal').count()>0;out.wholeSheet=(await page.locator('body').innerText()).includes('整張考卷 / 題目頁');const dup=await page.evaluate(()=>{const all=[...document.scripts].map(s=>s.src).filter(Boolean);return all.filter((x,i)=>all.indexOf(x)!==i)});out.duplicateScripts=dup;out.errors=w.errors;out.bad=w.bad;await page.screenshot({path:`${OUT}/desktop.png`,fullPage:true});results.desktop=out;if(!Object.entries(out).filter(([k])=>!['tutorRequestCount','duplicateScripts','errors','bad'].includes(k)).every(([,v])=>v===true)||out.tutorRequestCount!==1||dup.length||w.errors.length||w.bad.length)fail('DESKTOP_LIVE',out);await page.close()}
async function phoneQA(){const page=await browser.newPage({viewport:{width:390,height:844}}),w=watch(page);await load(page);const out={};out.home=(await page.locator('body').innerText()).includes('今天，把錯的真的改會');await openPage(page,'concepts');out.mobileTabs=await page.locator('.v5-mobile-pane-tabs').count()>0;await page.locator('[data-subject="biology"]').click();await page.waitForTimeout(120);for(const pane of ['outline','graph','detail']){const tab=page.locator(`[data-ce-mobile="${pane}"]`);if(await tab.count()&&await tab.isVisible()){await tab.click();await page.waitForTimeout(60)}out[`pane_${pane}`]=await page.locator(`[data-ce-pane="${pane}"]`).isVisible()}await openPage(page,'notebook');const p=page.locator('[data-problem]').first();if(await p.count()){await p.click();await page.waitForTimeout(120)}if(typeof await page.evaluate(()=>typeof v5TutorTestDemo)==='string'){}await page.evaluate(()=>window.v5TutorTestDemo?.({rightTrack:false,mode:'instructive'}));await page.waitForTimeout(120);const dock=page.locator('.v5-tutor-dock'),nav=page.locator('.mobile-nav');const dr=await dock.count()?await dock.boundingBox():null,nr=await nav.count()?await nav.boundingBox():null;out.tutorVisible=Boolean(dr);out.tutorNavOverlap=Boolean(dr&&nr&&Math.max(dr.x,nr.x)<Math.min(dr.x+dr.width,nr.x+nr.width)&&Math.max(dr.y,nr.y)<Math.min(dr.y+dr.height,nr.y+nr.height));out.noOverflow=await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2);out.mobileNav=await nav.count()>0;out.errors=w.errors;out.bad=w.bad;await page.screenshot({path:`${OUT}/phone.png`,fullPage:true});results.phone=out;if(!out.home||!out.mobileTabs||!out.pane_outline||!out.pane_graph||!out.pane_detail||!out.tutorVisible||out.tutorNavOverlap||!out.noOverflow||!out.mobileNav||w.errors.length||w.bad.length)fail('PHONE_LIVE',out);await page.close()}
await desktopQA();await phoneQA();await browser.close();fs.writeFileSync(`${OUT}/live.json`,JSON.stringify(results,null,2));if(failed)process.exit(1);
