function communityPage(){
  const s=activeSubject();const posts=state.community||[];
  return `<div class="page-head"><div><h2>社群討論</h2><p>討論附著在題目與概念上。先作答，再看別人怎麼想；私人筆記不會自動公開。</p></div><div class="page-actions"><button class="soft-btn" data-action="refreshCommunity">重新整理</button></div></div>${subjectTabs()}<div style="height:14px"></div><div class="community-layout"><div class="stack"><section class="panel composer"><textarea id="communityText" placeholder="分享你的解法、問一個卡住的點，或留下讓你記住這個概念的方法…"></textarea><div class="composer-foot"><span class="meta">公開內容 · Prototype 暫不允許貼外部連結。</span><button class="primary-btn" data-action="postCommunity">發布</button></div></section><section class="panel"><div class="panel-head"><h3>${s.name}社群</h3><span class="meta">${state.communityLoading?'載入中…':posts.length+' 則'}</span></div>${state.communityLoading?`<div class="empty">載入社群中…</div>`:posts.length?posts.map(postCard).join(''):`<div class="empty">這科目前還沒有貼文。你可以成為第一個。</div>`}</section></div><aside class="stack"><section class="panel"><div class="panel-head"><h3>社群不是另一個動態牆</h3></div><div class="mapping"><div class="callout">每一個互動都盡量回到學習：試做題目、修正敘述、分享自己的理解、或幫別人指出錯在哪。</div></div></section><section class="panel"><div class="panel-head"><h3>這科的熱門錯因</h3></div><div class="weakness-bars">${state.problems.filter(p=>p.subject===s.id).slice(0,5).map(p=>`<div class="bar-row" style="${subjectStyle(s.id)}"><span>${esc(p.mistakeType)}</span><div class="bar"><span style="width:${100-(p.mastery||50)}%"></span></div><strong>${100-(p.mastery||50)}%</strong></div>`).join('')||'<div class="empty">需要更多資料</div>'}</div></section></aside></div>`;
}
function postCard(p){return `<article class="post"><div class="post-avatar">${esc((p.display_name||p.displayName||'?')[0])}</div><div><strong>${esc(p.display_name||p.displayName||'同學')}</strong><p>${esc(p.body||'')}</p><div class="post-meta"><button class="helpful-btn" data-helpful="${esc(p.id||'')}">💡 ${(p.helpful_count||0)} 人覺得這讓我懂了</button><span>${p.created_at?new Date(p.created_at).toLocaleDateString('zh-TW'):''}</span></div></div></article>`}

function notesPage(){
  const notes=state.problems.filter(p=>p.insight).map(p=>({id:p.id,subject:p.subject,concept:p.concept,text:p.insight,title:p.title}));
  return `<div class="page-head"><div><h2>我的筆記與個人洞察</h2><p>保留你當時「為什麼會選錯」的思路。這些內容預設私人，而且可以刪除或重新整理。</p></div></div><div class="notes-grid">${notes.map(n=>`<section class="panel note-card" style="${subjectStyle(n.subject)}"><span class="tag">${subjectById(n.subject).name} · ${esc(n.concept)}</span><h4>${esc(n.title)}</h4><p>${esc(n.text)}</p><div class="note-footer"><button class="text-btn" data-problem="${n.id}">回原題</button><button class="danger-btn" data-action="deleteInsight" data-id="${n.id}">刪除筆記</button></div></section>`).join('')||'<div class="empty">還沒有私人筆記。</div>'}</div>`;
}

function analyticsPage(){
  const rows=SUBJECTS.map(s=>({s,mastery:subjectMastery(s.id),count:problemCount(s.id),mistakes:state.problems.filter(p=>p.subject===s.id).reduce((a,p)=>a+(p.attempts||1),0)}));
  return `<div class="page-head"><div><h2>弱點分析</h2><p>不只看「錯幾題」；同一概念反覆錯、需要提示、修正後仍記不起來，都會加重弱點權重。</p></div></div><div class="analytics-grid"><section class="panel"><div class="panel-head"><h3>各科掌握</h3><span class="meta">10 科</span></div><div class="weakness-bars">${rows.map(({s,mastery})=>`<div class="bar-row" style="${subjectStyle(s.id)}"><span>${s.name}</span><div class="bar"><span style="width:${mastery}%"></span></div><strong>${mastery}%</strong></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h3>本週訊號</h3></div><div class="stat-strip"><div class="stat-card"><strong>${mistakeCount()}</strong><span>累積錯誤事件</span></div><div class="stat-card"><strong>${Object.keys(state.mindHints||{}).length}</strong><span>心智題提示</span></div><div class="stat-card"><strong>${state.problems.filter(p=>p.due==='今天').length}</strong><span>今天待複習</span></div><div class="stat-card"><strong>${state.problems.filter(p=>Object.keys(p.corrections||{}).length).length}</strong><span>有修正敘述題</span></div></div></section><section class="panel" style="grid-column:1/-1"><div class="panel-head"><h3>錯題熱度</h3><span class="meta">顏色越深 = 越需要處理</span></div><div class="heatmap"><div></div>${['1','2','3','4','5','6','7','8'].map(x=>`<div class="meta" style="text-align:center">概念${x}</div>`).join('')}${SUBJECTS.map(s=>`<div class="label">${s.name}</div>${Array.from({length:8},(_,i)=>{const lvl=((problemCount(s.id)+i*2)%5);return `<div class="hcell ${lvl?'level'+lvl:''}">${lvl||''}</div>`}).join('')}`).join('')}</div></section></div>`;
}

function settingsPage(){
  const pubs=state.syllabus.level==='國中'?['康軒','翰林','南一','自訂']:['龍騰','翰林','南一','自訂'];
  return `<div class="page-head"><div><h2>課綱、出版社與資料</h2><p>先知道你在用哪一本，AI 才能把概念帶回真正課本位置。底層概念 ID 不隨出版社改變。</p></div></div><div class="settings-grid"><section class="panel settings-panel"><div class="grid-2"><div class="field"><label>學制</label><select id="levelSelect"><option ${state.syllabus.level==='高中'?'selected':''}>高中</option><option ${state.syllabus.level==='國中'?'selected':''}>國中</option></select></div><div class="field"><label>年級</label><input id="gradeInput" value="${esc(state.syllabus.grade)}" placeholder="例如 高二 / 國三"></div></div><div class="section-title"><h3>各科出版社</h3><small>可每科不同</small></div><div class="publisher-grid">${SUBJECTS.map(s=>`<div class="publisher-field"><strong>${s.name}</strong><select data-publisher="${s.id}">${pubs.map(p=>`<option ${activePublisher(s.id)===p?'selected':''}>${p}</option>`).join('')}</select></div>`).join('')}</div><button class="primary-btn" data-action="saveSettings" style="width:100%;margin-top:14px">儲存課綱設定</button><div class="callout" style="margin-top:12px">目前「精確章節對照」採確認式：AI 可以建議，但不會在資料庫沒有驗證時硬編章號。你確認後，該概念之後就能直接回到同一本課本位置。</div></section><aside class="stack"><section class="panel settings-panel"><h3 style="margin-top:0">資料備份</h3><p class="meta">私人錯題、筆記、手寫掌握訊號目前保存在這台裝置。可以匯出 JSON 備份，之後再接 Supabase 帳號同步。</p><div class="data-actions"><button class="soft-btn" data-action="exportData">${icon('download')} 匯出我的學習資料</button><button class="soft-btn" data-action="importData">${icon('upload')} 匯入備份</button><input id="importInput" class="hidden-input" type="file" accept="application/json"><button class="danger-btn" data-action="resetDemo">重設示範資料</button></div></section><section class="panel settings-panel"><h3 style="margin-top:0">目前後端</h3><div class="mapping-row"><span class="publisher">AI</span><span>interview aibot · Supabase Edge Function</span></div><div class="mapping-row"><span class="publisher">影像</span><span>Gemini vision / structured analysis</span></div><div class="mapping-row"><span class="publisher">社群</span><span>Supabase 公開討論資料表 + Edge Function</span></div></section></aside></div>`;
}

function captureModal(){return `<div class="modal-backdrop" id="captureModal"><div class="modal"><div class="modal-head"><h3>掃描錯題</h3><button class="icon-btn" data-action="closeCapture">${icon('close')}</button></div><div class="modal-body"><label class="dropzone" for="globalPhotoInput"><strong>📷 拍照或從相簿選題目</strong><p>AI 會辨識題目、你的作答、正確答案、錯誤敘述與概念。真正存入錯題本前一定要你確認。</p></label><img id="capturePreview" class="modal-preview" alt="題目預覽"><div class="callout warn" style="margin-top:12px">多選題例如你寫 AB、正解 ACE：系統會把「辨識到你的答案」和「AI 解出的正確答案」分開顯示，兩個都可改。</div><div class="modal-actions"><button class="soft-btn" data-action="loadDemoScan">載入示範掃描</button><button class="primary-btn" data-action="analyzePhoto">AI 分析這張</button></div></div></div></div>`}
