function conceptsPage(){
  const s=activeSubject();const ps=state.problems.filter(p=>p.subject===s.id);const concept=ps.find(p=>p.chapter===state.conceptChapter)||ps[0]||{concept:s.chapters[0],conceptCode:s.id.toUpperCase()+'-CORE',mastery:0,attempts:0,corrections:{}};
  const currentChapter=state.conceptChapter||concept.chapter||s.chapters[0];
  const truths=ps.flatMap(getCorrectedTruths).slice(0,7);
  return `<div class="page-head"><div><h2>各科概念地圖</h2><p>概念是主索引，出版社章節是回課本的導航。跨章題可以同時掛多個概念。</p></div></div>${subjectTabs()}<div style="height:14px"></div><div class="chapter-layout"><aside class="panel chapter-tree"><div class="chapter-subject">${s.name} · 108 課綱概念樹</div>${s.chapters.map(ch=>`<button class="chapter-node ${currentChapter===ch?'active':''}" data-concept-chapter="${esc(ch)}">${esc(ch)} <span class="meta">${ps.filter(p=>p.chapter===ch).length}</span></button>`).join('')}</aside><section class="panel concept-detail"><span class="concept-code">${esc(concept.conceptCode||s.id.toUpperCase()+'-CORE')}</span><h2>${esc(concept.concept||currentChapter)}</h2><p class="concept-summary">${s.name} · ${esc(currentChapter)}。這裡會聚合你在不同考卷、不同題型中犯過的同一類錯誤。</p><div class="concept-metrics"><div class="metric"><strong>${ps.filter(p=>p.chapter===currentChapter).length}</strong><span>相關錯題</span></div><div class="metric"><strong>${ps.filter(p=>p.chapter===currentChapter).reduce((a,p)=>a+(p.attempts||1),0)}</strong><span>錯誤事件</span></div><div class="metric"><strong>${ps.length?Math.round(ps.reduce((a,p)=>a+(p.mastery||50),0)/ps.length):0}%</strong><span>掌握度</span></div><div class="metric"><strong>${Object.keys(state.mindHints||{}).filter(k=>k.startsWith(s.id+':')).length}</strong><span>曾用提示節點</span></div></div><div class="grid-2"><div><h3>你的課本</h3><div class="mapping-row"><span class="publisher">出版社</span><span>${esc(activePublisher(s.id))}</span></div><div class="mapping-row"><span class="publisher">位置</span><span class="mapping-unknown">每個概念可由你確認章節位置；掃描題目時 AI 只提供建議，不會硬編章號。</span></div></div><div><h3>跨題型訊號</h3><p class="concept-summary">${concept.mistakeType?`你目前最常見的錯因：${esc(concept.mistakeType)}。`: '還需要更多作答資料，才會分析穩定弱點。'}</p></div></div><div class="truths"><h3>你已修正過的正確敘述</h3>${truths.length?truths.map(t=>`<div class="truth">✓ ${esc(t)}</div>`).join(''):'<div class="empty">這個概念還沒有修正敘述。</div>'}</div><div class="page-actions" style="margin-top:18px"><button class="soft-btn" data-page="notebook">看這科錯題</button><button class="primary-btn" data-page="mindmap">做這科心智題</button></div></section></div>`;
}
function mindmapPage(){
  const s=activeSubject();const map=MINDMAPS[s.id]||MINDMAPS.biology;const coords=[[28,34],[50,34],[72,34],[50,72]];const root=[50,12];
  const paths=coords.map(([x,y])=>`M ${root[0]} ${root[1]+5} L ${x} ${y-7}`).join(' ');
  return `<div class="page-head"><div><h2>心智題 · ${esc(map.title)}</h2><p>填空本身不是目的；「你在哪個節點需要提示」才是掌握度的重要訊號。</p></div><div class="page-actions"><button class="soft-btn" data-action="resetMind">清空這科</button></div></div>${subjectTabs()}<div style="height:14px"></div><section class="panel mindmap-wrap"><div class="mindmap-scroll"><div class="mindmap-stage"><svg class="mindmap-lines" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="${paths}"/></svg><div class="mind-node root" style="left:${root[0]}%;top:${root[1]}%"><strong>${esc(map.title)}</strong><small>${esc(map.subtitle)}</small></div>${map.nodes.map((n,i)=>mindNode(s.id,n,coords[i])).join('')}</div></div><div class="callout" style="margin-top:14px">按「圈這題，給我提示」會留下紀錄。完成一張心智圖不代表每個概念都能獨立叫出來；系統會把提示依賴納入後續複習。</div></section>`;
}
function mindNode(subjectId,n,coord){const key=subjectId+':'+n[0];const val=state.mindAnswers?.[key]||'';const hintUsed=state.mindHints?.[key];return `<div class="mind-node" style="left:${coord[0]}%;top:${coord[1]}%"><div class="question">${esc(n[1])}</div><input data-mind-key="${esc(key)}" data-answer="${esc(n[2])}" value="${esc(val)}" placeholder="自己填"><button class="hint-link" data-mind-hint="${esc(key)}" data-hint="${esc(n[3])}">圈這題，給我提示</button><div class="mind-status ${val===n[2]?'good':val?'bad':''}" id="status-${esc(key)}">${val===n[2]?'✓ 自己叫出來了':hintUsed?`提示已用：${esc(hintUsed)}`:''}</div></div>`}

function reviewPage(){
  const queue=dueProblems();const current=problemById(state.reviewProblemId)||queue[0]||selectedProblem();state.reviewProblemId=current?.id;
  return `<div class="page-head"><div><h2>複習計畫</h2><p>同一題可以重做；敘述型錯題會另外練「修正後的正確句子」。</p></div><div class="mode-switch"><button class="${state.reviewMode==='problem'?'active':''}" data-review-mode="problem">重做原題</button><button class="${state.reviewMode==='truth'?'active':''}" data-review-mode="truth">正確敘述</button></div></div><div class="review-layout"><aside class="panel review-queue"><div class="review-group-title">今天與近期</div>${queue.map(p=>`<button class="review-item ${p.id===current?.id?'active':''}" data-review-problem="${p.id}">${subjectById(p.subject).name} · ${esc(p.concept)}<div class="meta">${esc(p.due)}</div></button>`).join('')}</aside><section class="panel review-card">${current?(state.reviewMode==='problem'?redoProblem(current):truthReview(current)):'<div class="empty">目前沒有要複習的題目。</div>'}</section></div>`;
}
function redoProblem(p){const opts=[...(p.options||[])].sort((a,b)=>a[0].localeCompare(b[0]));return `<div style="max-width:760px;margin:0 auto"><div class="meta">${subjectById(p.subject).name} · ${esc(p.concept)} · 選項可重新排列</div><h2 style="margin:7px 0 16px">${esc(p.problemText)}</h2>${opts.length?opts.map(([l,t])=>{const sel=(state.reviewSelections||[]).includes(l);let cl=sel?'selected':'';if(state.reviewChecked)cl=(p.correct||[]).includes(l)?'correct':sel?'incorrect':'';return `<button class="redo-option ${cl}" data-review-option="${esc(l)}"><strong>${esc(l)}.</strong> ${esc(t)}</button>`}).join(''):`<div class="callout">這題不是選擇題。請先在紙上或題目畫布重做，再用 AI 家教核對步驟。</div>`}<div class="page-actions" style="justify-content:flex-end;margin-top:14px"><button class="soft-btn" data-action="reviewReset">清除</button><button class="primary-btn" data-action="checkReview">提交答案</button></div>${state.reviewChecked?`<div class="callout ${sameAnswers(state.reviewSelections,p.correct)?'success':'warn'}" style="margin-top:16px">你的答案：<strong>${esc((state.reviewSelections||[]).sort().join('')||'未作答')}</strong> · 正確：<strong>${esc((p.correct||[]).slice().sort().join(''))}</strong>。${sameAnswers(state.reviewSelections,p.correct)?'答對了；接下來看你能不能說出修正後的正確敘述。':'先找出哪個敘述需要被改正。'}</div>`:''}</div>`}
function truthReview(p){const truths=getCorrectedTruths(p);if(!truths.length)return `<div class="empty">這題沒有可抽成敘述複習的內容，請用「重做原題」。</div>`;const idx=clamp(state.truthIndex||0,0,truths.length-1);const truth=truths[idx];const words=truth.split(/\s+/);const blankWord=words.length>3?words[Math.floor(words.length/2)]:'';const blank=blankWord?truth.replace(blankWord,'________'):truth;return `<div class="fill-card"><div class="truth-label">✓ 已修正的正確敘述 · 現在記的是這個版本</div><div class="fill-sentence">${esc(blank)}</div><div class="tutor-input"><input id="truthAnswer" placeholder="把空白補起來（或用自己的話說）"><button class="primary-btn" data-action="truthCheck" data-expected="${esc(blankWord)}">檢查</button></div><div id="truthFeedback" style="margin-top:16px"></div><div class="page-actions" style="margin-top:15px"><button class="soft-btn" data-action="truthHint">給提示</button><button class="soft-btn" data-action="nextTruth">下一句</button></div></div>`}
function sameAnswers(a=[],b=[]){return [...a].sort().join('|')===[...b].sort().join('|')}

function tutorPage(){const p=selectedProblem();return `<div class="page-head"><div><h2>AI 家教</h2><p>不是把解答搬到另一頁；這裡的回覆會同時能回寫成題目上的圈、箭頭和手寫提示。</p></div><div class="page-actions"><button class="soft-btn" data-page="notebook">回原題畫布</button></div></div>${p?`<div class="workspace-grid"><div class="stack">${paperPanel(p)}</div><aside class="stack"><section class="panel"><div class="panel-head"><h3>${subjectById(p.subject).name} · ${esc(p.concept)}</h3><span class="meta">一步一步</span></div><div class="tutor"><div class="callout">你可以問「我哪一步錯？」、「只給提示」、「在圖上標出我要看的地方」。</div>${state.tutor?`<div class="tutor-answer" style="margin-top:12px">${esc(state.tutor.reply||'')}</div><div class="tutor-steps">${(state.tutor.steps||[]).map((x,i)=>`<div class="tutor-step"><span class="step-no">${i+1}</span><span>${esc(x)}</span></div>`).join('')}</div>${state.tutor.nextPrompt?`<div class="callout" style="margin-top:10px"><strong>下一個問題：</strong> ${esc(state.tutor.nextPrompt)}</div>`:''}`:''}<div class="tutor-input"><input id="tutorInput" placeholder="例如：不要直接告訴答案，先問我下一步"><button class="primary-btn" data-action="askTutor">問 AI</button></div></div></section><section class="panel"><div class="panel-head"><h3>你的掌握訊號</h3></div><div class="mapping"><div class="mapping-row"><span class="publisher">目前</span><span>${p.mastery}%</span></div><div class="mapping-row"><span class="publisher">錯因</span><span>${esc(p.mistakeType)}</span></div><div class="mapping-row"><span class="publisher">提示</span><span>${Object.keys(state.mindHints||{}).filter(k=>k.startsWith(p.subject+':')).length} 個心智題節點曾需提示</span></div></div></section></aside></div>`:'<div class="empty">先選一題錯題。</div>'}`}
