function notebookPage(){
  if(state.selectedProblemId && problemById(state.selectedProblemId)) return problemWorkspace(problemById(state.selectedProblemId));
  const ps=state.problems.filter(p=>p.subject===state.subject);
  return `<div class="page-head"><div><h2>我的錯題</h2><p>按科目、章節、概念整理。掃描進來的題目會先確認答案，再進錯題歷史。</p></div><div class="page-actions"><button class="primary-btn" data-action="capture">${icon('camera')} 掃描</button></div></div>${subjectTabs()}<div style="height:14px"></div><div class="notebook-layout"><aside class="panel filter-panel"><div class="filter-title">${activeSubject().name}章節</div><button class="filter-btn active" data-chapter="all"><span>全部</span><span>${ps.length}</span></button>${activeSubject().chapters.map(ch=>`<button class="filter-btn" data-chapter="${esc(ch)}"><span>${esc(ch)}</span><span>${ps.filter(p=>p.chapter===ch).length}</span></button>`).join('')}</aside><section class="panel"><div class="panel-head"><h3>${activeSubject().name}錯題</h3><span class="meta">${ps.length} 題 · 掌握 ${subjectMastery(state.subject)}%</span></div><div class="table-scroll"><table class="problem-table"><thead><tr><th>題目</th><th>概念</th><th>錯因</th><th>掌握</th><th>複習</th></tr></thead><tbody>${ps.map(p=>`<tr data-problem="${p.id}" data-problem-chapter="${esc(p.chapter)}"><td class="problem-title-cell"><strong>${esc(p.title)}</strong><small>${esc(p.problemText).slice(0,52)}${p.problemText.length>52?'…':''}</small></td><td>${esc(p.concept)}</td><td>${esc(p.mistakeType)}</td><td><span class="mastery"><span class="mastery-dot"></span>${p.mastery}%</span></td><td><span class="due ${p.due==='今天'?'red':''}">${esc(p.due)}</span></td></tr>`).join('')}</tbody></table></div>${ps.length?'':'<div class="empty">這科還沒有錯題。掃描第一題吧。</div>'}</section></div>`;
}
function problemWorkspace(p){
  const s=subjectById(p.subject);const isScan=p.id.startsWith('scan-');const answerLabels=[...new Set([...(p.options||[]).map(o=>o[0]),...(p.student||[]),...(p.correct||[])])];
  return `<div class="page-head"><div><button class="text-btn" data-action="backNotebook">← 回${s.name}錯題</button><h2>${esc(p.title)}</h2><p>${s.name} · ${esc(p.chapter)} · ${esc(p.concept)} · 錯 ${p.attempts||1} 次</p></div><div class="page-actions"><button class="soft-btn" data-page="review">加入複習</button><button class="soft-btn" data-page="community">討論</button></div></div>
  <div class="workspace-grid"><div class="stack">${paperPanel(p)}${correctionPanel(p)}${insightPanel(p)}</div><aside class="stack">${recognitionPanel(p,answerLabels,isScan)}${mappingPanel(p)}${tutorMiniPanel(p)}${reviewSchedulePanel(p)}</aside></div>`;
}
function scanLikelyHasFigure(p){const raw=`${p?.problemText||''} ${(state.scan?.recognitionNote)||''}`;return Boolean(state.scan?.hasDiagram||state.scan?.hasFigure||state.scan?.diagram||state.scan?.figure||/(附圖|上圖|下圖|右圖|左圖|圖中|如圖|示意圖|關係圖|剖面圖|座標圖|曲線圖|圖表|表格|diagram|graph|figure|chart)/i.test(raw))}
function paperPanel(p){
  const isScan=p.id.startsWith('scan-')&&state.scanImage;const overlays=(state.annotations||[]).map(a=>`<div class="ai-overlay-note" style="left:${clamp(Number(a.x)||8,2,78)}%;top:${clamp(Number(a.y)||8,2,86)}%">${esc(a.text||'')}</div>`).join('');
  const opts=(p.options||[]).map(([l,t])=>`<div class="paper-option ${(p.student||[]).includes(l)?'student':''}"><strong>${esc(l)}.</strong> ${esc(t)}</div>`).join('');
  const figure=Boolean(isScan&&scanLikelyHasFigure(p));
  const reconstructed=isScan?`<div class="paper-demo" style="min-height:0;padding-bottom:28px"><div class="meta" style="margin-bottom:9px">AI 重建題目 · 文字與選項可核對</div><h4>${esc(p.problemText||'未辨識到題幹')}</h4><div class="options">${opts}</div><div class="hand-note">辨識到你的答案：${esc((p.student||[]).join('')||'未作答')}</div><details ${figure?'open':''} style="margin-top:18px;border-top:1px solid #e4e4e8;padding-top:12px"><summary style="cursor:pointer;font-weight:800;color:#65616d">${figure?'題目附圖 / 原始圖表':'查看原始圈選（核對用）'}</summary><div class="meta" style="margin:7px 0 9px">${figure?'圖形先保留原始圈選，避免 AI 重畫造成資訊錯誤。':'需要時再打開原始圈選，重建題目仍以文字為主。'}</div><img class="scan-photo" src="${state.scanImage}" alt="學生圈選的原始題目" style="position:static;display:block;width:100%;height:auto;max-height:560px;object-fit:contain;border-radius:12px"></details></div>`:'';
  return `<section class="panel"><div class="panel-head"><h3>${isScan?'重建後的題目':'原題就是工作紙'}</h3><div class="meta">Apple Pencil / 觸控 / 滑鼠 · AI 也寫在這裡</div></div><div class="paper" id="paper">${isScan?reconstructed:`<div class="paper-demo"><h4>${esc(p.problemText)}</h4><div class="options">${opts}</div><div class="hand-note">我的答案：${esc((p.student||[]).join('')||'未作答')}</div></div>`}${overlays}<canvas id="drawCanvas" class="canvas-layer"></canvas><div class="paper-toolbar"><div class="toolset"><button class="tool active" data-tool="pen">✎</button><button class="tool" data-tool="eraser">⌫</button><button class="tool" data-action="undoInk">↶</button><button class="tool" data-action="clearInk">清除</button></div><div class="toolset"><button class="tool" data-action="aiOnPaper">✦ AI 在題目上提示</button></div></div></div></section>`;
}
function recognitionPanel(p,labels,isScan){
  const student=isScan?state.scanStudent:p.student||[];const correct=isScan?state.scanCorrect:p.correct||[];
  return `<section class="panel"><div class="panel-head"><h3>答案辨識 ${isScan?'· 必須確認':''}</h3><span class="meta">${isScan?'AI ≠ 真相，先讓你核對':'已確認紀錄'}</span></div><div class="recognition"><div class="recognition-row"><div class="recognition-label"><strong>我們辨識到你作答</strong><span class="confidence">${isScan?`${Math.round((state.scan?.recognizedAnswerConfidence||0)*100)}% 信心`:'已確認'}</span></div><div class="chips">${labels.map(l=>`<button class="chip student ${student.includes(l)?'on':''}" ${isScan?`data-scan-student="${esc(l)}"`:'disabled'}>${esc(l)}</button>`).join('')}</div></div><div class="recognition-row"><div class="recognition-label"><strong>正確答案</strong><span class="confidence">${isScan?`${Math.round((state.scan?.correctAnswerConfidence||0)*100)}% 信心`:'已確認'}</span></div><div class="chips">${labels.map(l=>`<button class="chip ${correct.includes(l)?'on':''}" ${isScan?`data-scan-correct="${esc(l)}"`:'disabled'}>${esc(l)}</button>`).join('')}</div></div>${isScan&&state.scan?.recognitionNote?`<div class="callout warn" style="margin-top:10px">${esc(state.scan.recognitionNote)}</div>`:''}</div>${isScan?`<div class="confirm-box"><button class="primary-btn" data-action="confirmScan">我確認以上作答與正解</button></div>`:''}</section>`;
}
function correctionPanel(p){
  const opts=p.options||[];const corr=p.corrections||{};if(!opts.length&&!Object.keys(corr).length)return `<section class="panel"><div class="panel-head"><h3>修正 → 記住正確</h3></div><div class="empty">這題不是敘述型題目。系統會保留正解步驟與你的錯因，供重做與家教使用。</div></section>`;
  const rows=opts.map(([l,text])=>{const isCorrect=(p.correct||[]).includes(l);const fixed=corr[l]||text;return `<div class="statement"><div class="statement-label ${isCorrect?'good':'bad'}">${esc(l)}</div><div><div class="original">${isCorrect?'原句已正確':'原句（錯誤）：'} ${esc(text)}</div><textarea class="corrected-input" data-correction="${esc(l)}" ${isCorrect?'readonly':''}>${esc(fixed)}</textarea><div class="truth-label">✓ ${isCorrect?'正確，保留':'你要記的是修正後這句'}</div></div><div class="statement-actions">${isCorrect?'':`<button class="soft-btn" data-ai-revise="${esc(l)}">AI 修正</button>`}</div></div>`}).join('');
  return `<section class="panel"><div class="panel-head"><h3>把每個敘述改成正確的，再記正確版本</h3><button class="text-btn" data-action="saveTruths">存入正確敘述庫</button></div><div class="correction-list">${rows}</div><div class="callout success" style="margin:0 15px 15px">原題可以保留錯誤選項讓你重做；長期複習時，系統會優先讓你回想「修正後的正確敘述」。</div></section>`;
}
function insightPanel(p){return `<section class="panel"><div class="panel-head"><h3>我當時怎麼想？</h3><span class="meta">私人 · 可刪除</span></div><div class="insight-box"><textarea id="insightText" placeholder="用你自己的話留下當時的想法或錯因…">${esc(p.insight||'')}</textarea><div class="insight-actions"><button class="soft-btn" data-action="cleanInsight">AI 幫我去掉廢話</button><button class="primary-btn" data-action="saveInsight">儲存我的說法</button></div></div></section>`}
function mappingPanel(p){
  const publisher=activePublisher(p.subject);const suggested=p.aiChapterHint||'';const location=p.bookLocation||'';
  return `<section class="panel"><div class="panel-head"><h3>概念 → 你的課本位置</h3><button class="text-btn" data-action="editBookLocation">設定位置</button></div><div class="mapping"><span class="concept-code">${esc(p.conceptCode||'CONCEPT')}</span><div class="concept-name">${esc(p.concept)}</div><div class="meta">${subjectById(p.subject).name} · 108 課綱概念層</div><div class="mapping-row"><span class="publisher">你使用</span><span><strong>${esc(publisher)}</strong></span></div><div class="mapping-row"><span class="publisher">課本位置</span><span>${location?`<strong>${esc(location)}</strong>`:`<span class="mapping-unknown">尚未確認 — 點「設定位置」後就能直接回課本找</span>`}</span></div>${suggested?`<div class="mapping-row"><span class="publisher">AI 建議</span><span>${esc(suggested)}</span></div>`:''}<div class="callout" style="margin-top:10px">底層先用概念 ID。出版社只負責把同一概念映射回你真正使用的課本章節，避免被版本綁死。</div></div></section>`;
}
function tutorMiniPanel(p){const t=state.tutor;return `<section class="panel"><div class="panel-head"><h3>AI 家教 · 就寫在題目旁</h3><button class="text-btn" data-page="tutor">打開完整家教</button></div><div class="tutor">${t?`<div class="tutor-answer">${esc(t.reply||'')}</div><div class="tutor-steps">${(t.steps||[]).slice(0,3).map((x,i)=>`<div class="tutor-step"><span class="step-no">${i+1}</span><span>${esc(x)}</span></div>`).join('')}</div>`:`<div class="callout">先不把答案整段倒給你。AI 會先在原題上圈重點、畫箭頭、問下一步。</div>`}<div class="tutor-input"><input id="miniTutorInput" placeholder="例如：我卡在哪一步？"><button class="primary-btn" data-action="askMiniTutor">問 AI</button></div></div></section>`}
function reviewSchedulePanel(p){return `<section class="panel"><div class="panel-head"><h3>複習安排</h3><span class="meta">概念掌握 ${p.mastery||50}%</span></div><div class="mapping"><div class="mapping-row"><span class="publisher">下次</span><span><strong>${esc(p.due||'今天')}</strong></span></div><div class="mapping-row"><span class="publisher">會出現</span><span>原題重做 + 修正敘述 + 心智題節點</span></div><button class="soft-btn" data-page="review" style="width:100%;margin-top:10px">看完整複習計畫</button></div></section>`}
