// Semantic v5 QA. Capture the strict E2E flag, then prevent the obsolete v4 expectations from running.
(async()=>{
 const run=Boolean(window.__v4StrictRunE2E);if(!run)return;window.__v4StrictRunE2E=false;
 const sleep=ms=>new Promise(r=>setTimeout(r,ms)),results=[],check=(name,ok,detail='')=>results.push({name,ok:Boolean(ok),detail});
 const mobile=()=>innerWidth<=860;
 const nav=async page=>{let target;if(mobile()){document.querySelector('.mobile-nav [data-action="toggleMenu"]')?.click();await sleep(80);target=document.querySelector(`.mobile-drawer [data-page="${page}"]`)}else target=document.querySelector(`.sidebar [data-page="${page}"]`);if(!target)throw Error(`missing nav ${page}`);target.click();await sleep(220)};
 try{
  await sleep(280);check('home renders',document.body.innerText.includes('今天，把錯的真的改會'));await nav('mindmap');check('canonical curriculum map renders',Boolean(document.querySelector('.v4tb-sheet')));check('ten subjects remain',new Set([...document.querySelectorAll('[data-subject]')].map(x=>x.dataset.subject).filter(Boolean)).size===10);
  const earth=document.querySelector('[data-subject="earth"]');if(!earth)throw Error('earth tab missing');earth.click();await sleep(300);
  const counts=window.v4RefValidateData?.(),sem=window.v5SemanticValidate?.();check('276 source prompts',counts?.ok&&counts.total===276&&counts.expectedTotal===276,JSON.stringify(counts));check('semantic validation passes',Boolean(sem?.ok),JSON.stringify(sem));check('six semantic chapters',window.EARTH_SEMANTIC_MAPS?.length===6);check('fixed two-page spread',document.querySelectorAll('[data-semantic-page]').length===2&&document.querySelectorAll('.v4ref-paper').length===2);check('semantic canvas',Boolean(document.querySelector('.v5-semantic-canvas')));
  check('question semantic metadata',[...document.querySelectorAll('.v5-recall')].every(x=>x.dataset.concept&&x.dataset.placementReason));check('figure semantic metadata',[...document.querySelectorAll('.v5-figure')].every(x=>x.dataset.concepts&&x.dataset.purpose));check('edge semantic metadata',[...document.querySelectorAll('.v5-edge-group')].every(x=>x.dataset.edge&&x.dataset.relation&&x.dataset.reason));
  for(const k of ['orphanQuestions','orphanConceptNodes','orphanRequiredFigures','orphanConnectors','connectorWithoutRelationMeaning','sourceRequiredFiguresMissing','unverifiedInventedFigures'])check(`${k} empty`,Array.isArray(sem?.[k])&&sem[k].length===0,JSON.stringify(sem?.[k]));
  check('chapter 1 count',document.querySelectorAll('.v5-recall').length===48);document.querySelector('[data-v4ref-chapter="2"]')?.click();await sleep(180);check('chapter 2 count',document.querySelectorAll('.v5-recall').length===50);check('chapter 2 numbers stop at 50',!document.querySelector('[data-question="51"]'));
  for(const n of [3,4,5,6]){document.querySelector(`[data-v4ref-chapter="${n}"]`)?.click();await sleep(150);check(`chapter ${n} count`,document.querySelectorAll('.v5-recall').length===window.V5_COUNTS[n]);check(`chapter ${n} figures`,document.querySelectorAll('.v5-figure').length===window.EARTH_SEMANTIC_MAPS[n-1].figures.length);check(`chapter ${n} edges`,document.querySelectorAll('.v5-edge-group').length===window.EARTH_SEMANTIC_MAPS[n-1].relations.length)}
  check('chapter 5 source order preserved',Boolean(window.v4RefValidateData?.().ch5OrderOk));check('fixed spatial layout on mobile',getComputedStyle(document.querySelector('[data-semantic-page]')).position==='absolute');check('pan zoom controls',document.querySelectorAll('[data-v4ref-zoom]').length===4);check('no source page bitmap in normal render',![...document.querySelectorAll('img')].some(x=>/IMG_15\d\d/i.test(x.src||'')));
  document.querySelector('[data-v4ref-source="curriculum"]')?.click();await sleep(170);check('108 curriculum remains',Boolean(document.querySelector('.v4tb-sheet')));await nav('review');check('review remains',document.body.innerText.includes('修正後正確敘述'));await nav('notes');check('notes remain',document.body.innerText.includes('獨立筆記系統'));await nav('analytics');check('analytics remain',document.body.innerText.includes('最需要處理的概念'));await nav('settings');check('sync remains',document.body.innerText.includes('帳號與跨裝置同步'));
  const failed=results.filter(x=>!x.ok),box=document.createElement('pre');box.id='e2e-results';box.dataset.status=failed.length?'FAIL':'PASS';box.textContent=JSON.stringify({status:failed.length?'FAIL':'PASS',semantic:sem,results},null,2);document.body.appendChild(box);
 }catch(err){const box=document.createElement('pre');box.id='e2e-results';box.dataset.status='FAIL';box.textContent=JSON.stringify({status:'FAIL',error:String(err),results},null,2);document.body.appendChild(box)}
})();
