const MINDMAPS={
 biology:{title:'細胞呼吸',subtitle:'能量轉換總覽',nodes:[['n1','第一階段發生在哪？','細胞質','細'],['n2','葡萄糖先被分解成？','丙酮酸','丙'],['n3','電子傳遞鏈在哪？','粒線體內膜','粒'],['n4','最終主要能量貨幣？','ATP','A']]},
 math:{title:'條件機率',subtitle:'先縮小樣本空間',nodes:[['n1','條件機率的分母是？','P(B)','B'],['n2','分子是 A 與 B 的？','交集','交'],['n3','P(A|B) 的意思？','已知B發生時A的機率','已'],['n4','反向條件常用什麼公式？','貝氏定理','貝']]},
 physics:{title:'牛頓運動定律',subtitle:'受力 → 加速度',nodes:[['n1','受力分析第一步？','選定研究物體','物'],['n2','合力與加速度關係？','F=ma','F'],['n3','靜止時加速度？','0','0'],['n4','靜摩擦力會怎樣？','隨需求調整至上限','隨']]},
 chemistry:{title:'酸鹼平衡',subtitle:'物種、平衡、pH',nodes:[['n1','強酸主要特徵？','近乎完全解離','完'],['n2','Ka 越大代表？','酸性越強','強'],['n3','緩衝液通常包含？','弱酸與共軛鹼','弱'],['n4','中和本質常看哪個粒子？','H+與OH-','H']]},
 chinese:{title:'閱讀理解',subtitle:'文本證據與作者觀點',nodes:[['n1','先找文章的核心？','主旨','主'],['n2','支持主旨的材料？','文本證據','證'],['n3','判斷語氣要看？','用字與情境','用'],['n4','選項若過度延伸？','回到原文驗證','原']]},
 english:{title:'篇章閱讀',subtitle:'meaning before translation',nodes:[['n1','先抓每段的？','topic sentence','t'],['n2','轉折詞通常表示？','關係改變','關'],['n3','代名詞要回找？','antecedent','a'],['n4','陌生字先用什麼？','context clues','c']]},
 earth:{title:'板塊運動',subtitle:'邊界 → 地形 → 災害',nodes:[['n1','張裂型常形成？','中洋脊','中'],['n2','聚合型可能形成？','海溝或造山帶','海'],['n3','錯動型主要運動？','水平錯動','水'],['n4','地震多集中在哪？','板塊邊界','板']]},
 history:{title:'歷史因果',subtitle:'事件不是孤立年份',nodes:[['n1','先定位事件的？','時空背景','時'],['n2','短期引爆因素？','導火線','導'],['n3','制度或結構因素？','長期原因','長'],['n4','比較結果要分？','短期與長期影響','短']]},
 geography:{title:'人口與都市',subtitle:'分布、移動、影響',nodes:[['n1','人口密度看什麼？','人口/面積','人'],['n2','推力與拉力描述？','遷移原因','遷'],['n3','都市化常伴隨？','產業結構改變','產'],['n4','空間分布常用？','地圖與GIS','地']]},
 civics:{title:'市場與價格',subtitle:'誘因與資源配置',nodes:[['n1','價格上升通常使供給？','增加','增'],['n2','價格上升通常使需求量？','減少','減'],['n3','均衡點是供需？','相等','相'],['n4','外部成本可能導致？','市場失靈','市']]}
};

const SEED_PROBLEMS=[
 {id:'bio-1',subject:'biology',title:'細胞呼吸敘述複選',concept:'細胞呼吸',conceptCode:'BIO-CELL-RESP',chapter:'細胞呼吸與光合作用',student:['A','B'],correct:['A','C','E'],mastery:62,due:'今天',mistakeType:'概念混淆',attempts:2,problemText:'下列關於細胞呼吸的敘述，哪些正確？（複選）',options:[['A','葡萄糖在細胞質中進行糖解作用，產生丙酮酸。'],['B','丙酮酸進入粒線體後，於基質中進行電子傳遞鏈。'],['C','電子傳遞鏈主要位於粒線體內膜。'],['D','氧氣在有氧呼吸過程中被產生。'],['E','ATP 合成酶利用質子梯度合成 ATP。']],corrections:{B:'丙酮酸進入粒線體後，克氏循環主要在粒線體基質進行；電子傳遞鏈位於粒線體內膜。',D:'氧氣在有氧呼吸的電子傳遞鏈中作為最終電子受體而被消耗。'},insight:'我常把克氏循環和電子傳遞鏈的位置搞混。'},
 {id:'phy-1',subject:'physics',title:'撤去 F₂ 後的靜摩擦力',concept:'靜摩擦力',conceptCode:'PHY-NEWTON-FRICTION',chapter:'牛頓運動定律',student:['A','B'],correct:['C'],mastery:48,due:'今天',mistakeType:'條件改變後未重畫受力圖',attempts:3,problemText:'木塊原本受 F₁=10N、F₂=2N 且靜止。撤去 F₂ 後，若木塊仍靜止，合力與摩擦力為何？',options:[['A','合力方向向右。'],['B','摩擦力仍為 8N。'],['C','合力為 0，摩擦力調整為 10N 向左。'],['D','摩擦力為 12N。']],corrections:{A:'若木塊撤去 F₂ 後仍保持靜止，合力仍為 0。',B:'撤去 F₂ 後若仍靜止，靜摩擦力會調整為 10N 向左。',D:'撤去 F₂ 後若仍靜止，靜摩擦力為 10N，不是 12N。'},insight:'我沿用了撤去 F₂ 前的摩擦力，忘記條件變了要重新平衡。'},
 {id:'math-1',subject:'math',title:'條件機率與樣本空間',concept:'條件機率',conceptCode:'MATH-PROB-COND',chapter:'排列組合與機率',student:['B'],correct:['D'],mastery:38,due:'今天',mistakeType:'分母樣本空間未縮小',attempts:4,problemText:'已知事件 B 已發生，求事件 A 發生的條件機率。',options:[['A','P(A)'],['B','P(A∩B)'],['C','P(B)/P(A)'],['D','P(A∩B)/P(B)']],corrections:{B:'條件機率 P(A|B) 的分子是 P(A∩B)，但仍要除以已知條件 B 的機率 P(B)。'},insight:'我看到交集就直接選，沒有先把樣本空間縮成 B。'},
 {id:'chem-1',subject:'chemistry',title:'緩衝液與 pH',concept:'緩衝溶液',conceptCode:'CHEM-ACIDBASE-BUFFER',chapter:'酸鹼平衡',student:['A'],correct:['C'],mastery:52,due:'明天',mistakeType:'公式套用',attempts:2,problemText:'下列何者最能形成緩衝溶液？',options:[['A','強酸與強鹼等莫耳混合'],['B','純水'],['C','弱酸與其共軛鹼適量共存'],['D','只有強酸']],corrections:{A:'強酸與強鹼等莫耳完全中和後通常不構成典型緩衝系統。'},insight:'我只想到「酸+鹼」而沒有看是不是弱酸/共軛鹼。'},
 {id:'eng-1',subject:'english',title:'關係子句 which / that',concept:'關係子句',conceptCode:'ENG-GRAMMAR-RELATIVE',chapter:'文法與句型',student:['A'],correct:['B'],mastery:64,due:'2 天後',mistakeType:'句型辨識',attempts:1,problemText:'Choose the grammatically correct sentence.',options:[['A','The book which I bought it yesterday was expensive.'],['B','The book which I bought yesterday was expensive.'],['C','The book I bought it yesterday was expensive.'],['D','The book which bought yesterday was expensive.']],corrections:{A:'The book which I bought yesterday was expensive.',C:'The book I bought yesterday was expensive.',D:'The book which I bought yesterday was expensive.'},insight:'關代已經代替受詞時，不能再多放 it。'},
 {id:'chi-1',subject:'chinese',title:'文言語意判讀',concept:'文言文語意',conceptCode:'CHI-CLASSICAL-MEANING',chapter:'文言文閱讀',student:['C'],correct:['A'],mastery:58,due:'3 天後',mistakeType:'古今義混淆',attempts:2,problemText:'依上下文判斷畫線詞義，何者正確？',options:[['A','依語境判斷詞義'],['B','直接套現代常用義'],['C','只看單字不看句意'],['D','以字形猜測']],corrections:{C:'文言詞義應結合句法與上下文判斷，不能只看單字。'},insight:'我會被現代常用義帶走。'},
 {id:'earth-1',subject:'earth',title:'板塊邊界與海溝',concept:'板塊構造',conceptCode:'EARTH-TECTONICS',chapter:'板塊與地質作用',student:['B'],correct:['C'],mastery:55,due:'4 天後',mistakeType:'地形對應混淆',attempts:2,problemText:'海洋板塊隱沒到另一板塊下方時，常見何種地形？',options:[['A','中洋脊'],['B','裂谷'],['C','海溝'],['D','沙丘']],corrections:{B:'裂谷較常與張裂型板塊邊界或大陸張裂相關；隱沒帶常伴隨海溝。'},insight:'我把張裂和聚合的地形搞混。'},
 {id:'hist-1',subject:'history',title:'事件因果排序',concept:'歷史因果',conceptCode:'HIST-CAUSE-EFFECT',chapter:'近代國家形成',student:['D'],correct:['B'],mastery:44,due:'5 天後',mistakeType:'時間線混淆',attempts:3,problemText:'判斷事件的先後與因果關係。',options:[['A','先看結果再猜年份'],['B','先定位時空背景，再區分長期原因、導火線與影響'],['C','只記單一年份'],['D','把所有事件視為獨立']],corrections:{D:'歷史事件通常應放在時空背景與因果鏈中理解，不能視為彼此完全獨立。'},insight:'我背年份但沒有把事件連起來。'},
 {id:'geo-1',subject:'geography',title:'人口遷移推拉因素',concept:'人口遷移',conceptCode:'GEO-POP-MIGRATION',chapter:'人口',student:['A'],correct:['C'],mastery:59,due:'6 天後',mistakeType:'概念定義',attempts:1,problemText:'何者最適合解釋人口遷移的推力與拉力？',options:[['A','只有距離'],['B','只有人口密度'],['C','原居地不利條件與目的地吸引條件共同作用'],['D','完全隨機']],corrections:{A:'人口遷移通常受原居地推力與目的地拉力等多重因素影響，不只距離。'},insight:'我把遷移簡化成距離問題。'},
 {id:'civ-1',subject:'civics',title:'價格上限與市場結果',concept:'市場干預',conceptCode:'CIV-ECON-PRICE-CONTROL',chapter:'市場與價格',student:['B'],correct:['D'],mastery:46,due:'7 天後',mistakeType:'供需圖判讀',attempts:3,problemText:'若具約束力的價格上限低於均衡價格，最可能出現？',options:[['A','供過於求'],['B','均衡不變'],['C','需求量下降且供給量上升'],['D','供不應求']],corrections:{B:'具約束力的價格上限低於均衡價格時，市場通常會出現需求量大於供給量的短缺。'},insight:'我會忘記價格上限是「低於均衡」才有約束力。'}
];
