// Remaining V3 product behaviors: first-class notes and non-choice review.
state.notes=Array.isArray(state.notes)?state.notes:[];
state.writtenReviewFeedback=state.writtenReviewFeedback||{};

function v3SaveProblemNote(){const p=selectedProblem(),text=document.getElementById('insightText')?.value.trim();if(!p||!text)return toast('先寫下你的想法');const id=`note-${p.id}-${Date.now().toString(36)}`;state.notes.push({id,problemId:p.id,subject:p.subject,concept:p.concept,conceptCode:p.conceptCode,title:p.title,text,createdAt:new Date().toISOString(),kind:'個人錯因'});save();render();toast('已另存成可獨立整理的概念筆記')}
function v3CreateManualNote(){const text=document.getElementById('newNoteText')?.value.trim(),title=document.getElementById('newNoteTitle')?.value.trim()||'我的筆記';if(!text)return toast('先寫一點內容');const s=activeSubject(),p=selectedProblem()?.subject===s.id?selectedProblem():null;state.notes.unshift({id:uid('note'),problemId:p?.id||null,subject:s.id,concept:p?.concept||'',conceptCode:p?.conceptCode||'',title,text,createdAt:new Date().toISOString(),kind:'自由筆記'});save();render();toast('筆記已儲存')}
function v3DeleteNote(id){state.notes=state.notes.filter(n=>n.id!==id);save();render();toast('已刪除筆記')}

function insightPanel(p){return `<section class="panel"><div class="panel-head"><h3>我當時怎麼想？</h3><span class="meta">私人 · 可刪除</span></div><div class="insight-box"><textarea id="insightText" placeholder="用你自己的話留下當時的想法或錯因…">${esc(p.insight||'')}</textarea><div class="insight-actions"><button class="soft-btn" data-action="cleanInsight">AI 幫我整理語句</button><button class="soft-btn" data-action="saveAsNote">另存概念筆記</button><button class="primary-btn" data-action="saveInsight">儲存我的說法</button></div></div></section>`}
function notesPage(){
  const subjectNotes=state.notes.filter(n=>!n.subject||n.subject===state.subject),legacy=state.problems.filter(p=>p.insight&&p.subject===state.subject).map(p=>({id:'legacy-'+p.id,problemId:p.id,subject:p.subject,concept:p.concept,title:p.title,text:p.insight,kind:'錯題洞察',legacy:true}));const notes=[...subjectNotes,...legacy];
  return `<div class="page-head"><div><h2>我的筆記</h2><p>現在是獨立筆記系統，不再只是錯題上的一句 insight。筆記可以連回題目與概念，但本身保持私人。</p></div></div>${subjectTabs()}<div style="height:14px"></div><section class="panel v3-note-composer"><div class="grid-2"><input id="newNoteTitle" placeholder="筆記標題"><div class="meta">${esc(activeSubject().name)}${selectedProblem()?.subject===state.subject?` · 目前連結：${esc(selectedProblem().concept)}`:''}</div></div><textarea id="newNoteText" placeholder="寫下你真正想留住的理解、解題判斷、易混淆點…"></textarea><div class="page-actions" style="justify-content:flex-end"><button class="primary-btn" data-action="createNote">儲存筆記</button></div></section><div class="notes-grid" style="margin-top:14px">${notes.map(n=>`<section class="panel note-card" style="${subjectStyle(n.subject||state.subject)}"><span class="tag">${esc(n.kind||'筆記')}${n.concept?' · '+esc(n.concept):''}</span><h4>${esc(n.title)}</h4><p>${esc(n.text)}</p><div class="note-footer">${n.problemId?`<button class="text-btn" data-problem="${esc(n.problemId)}">回原題</button>`:''}${n.legacy?'<span class="meta">原題洞察</span>':`<button class="danger-btn" data-delete-note="${esc(n.id)}">刪除筆記</button>`}</div></section>`).join('')||'<div class="empty">這科還沒有筆記。</div>'}</div>`;
}

function redoProblem(p){
  const opts=v3StableShuffle(p.options||[],`${p.id}:${state.reviewShuffleSeed||'v3'}`);
  if(opts.length){return `<div style="max-width:760px;margin:0 auto"><div class="meta">${subjectById(p.subject).name} · ${esc(p.concept)} · 選項順序每輪會重新排列</div><h2 style="margin:7px 0 16px">${esc(p.problemText)}</h2>${opts.map(([l,t])=>{const sel=(state.reviewSelections||[]).includes(l);let cl=sel?'selected':'';if(state.reviewChecked)cl=(p.correct||[]).includes(l)?'correct':sel?'incorrect':'';return `<button class="redo-option ${cl}" data-review-option="${esc(l)}"><strong>${esc(l)}.</strong> ${esc(t)}</button>`}).join('')}<div class="page-actions" style="justify-content:flex-end;margin-top:14px"><button class="soft-btn" data-action="reviewReset">清除</button><button class="primary-btn" data-action="checkReview">提交答案</button></div>${state.reviewChecked?`<div class="callout ${sameAnswers(state.reviewSelections,p.correct)?'success':'warn'}" style="margin-top:16px">你的答案：<strong>${esc((state.reviewSelections||[]).slice().sort().join('')||'未作答')}</strong> · 正確：<strong>${esc((p.correct||[]).slice().sort().join(''))}</strong>。${sameAnswers(state.reviewSelections,p.correct)?`下一次：${esc(p.due)}`:'這題會更快排回來。'}</div>`:''}</div>`}
  const fb=state.writtenReviewFeedback[p.id];return `<div style="max-width:760px;margin:0 auto"><div class="meta">${subjectById(p.subject).name} · ${esc(p.concept)} · 非選擇題</div><h2 style="margin:7px 0 16px">${esc(p.problemText)}</h2><textarea id="writtenReviewInput" class="v3-written-answer" placeholder="寫下答案、推理或計算結果。若你比較想手寫，可回原題工作紙用 Apple Pencil 寫，再叫 AI 家教看筆跡。"></textarea><div class="page-actions" style="justify-content:flex-end;margin-top:12px"><button class="soft-btn" data-problem="${esc(p.id)}">回原題手寫</button><button class="primary-btn" data-action="checkWrittenReview" data-id="${esc(p.id)}">AI 核對我的作答</button></div>${fb?`<div class="callout ${fb.signal==='strong'?'success':fb.signal==='weak'?'warn':''}" style="margin-top:16px"><strong>${fb.signal==='strong'?'✓ 作答正確':fb.signal==='medium'?'△ 大致正確，還有一處要補':'再修一次'}</strong><br>${esc(fb.reply||'')}${fb.nextPrompt?`<br><small>下一步：${esc(fb.nextPrompt)}</small>`:''}</div>`:''}</div>`;
}
async function v3CheckWrittenReview(id){const p=problemById(id),answer=document.getElementById('writtenReviewInput')?.value.trim();if(!p||!answer)return toast('先寫下你的作答');try{toast('AI 正在依題目核對你的作答…');const original=await v3GetImage(p.id),body={problemText:p.problemText,question:`這是複習核對，不要先教答案。請判斷學生作答「${answer}」是否正確：完全正確 masterySignal=strong；核心正確但不完整=medium；錯誤=weak。reply 用臺灣高中自然用語指出最關鍵的一點。`,studentAnswer:[answer],correctAnswer:p.correct||[]};if(original?.base64){body.imageBase64=original.base64;body.mimeType=original.mimeType||'image/jpeg'}const r=await apiCall('/tutor',body),signal=r.result.masterySignal||'unknown';state.writtenReviewFeedback[p.id]={signal,reply:r.result.reply||'',nextPrompt:r.result.nextPrompt||'',at:new Date().toISOString()};if(signal==='strong')v3Schedule(p,true,'none');else if(signal==='medium')v3Schedule(p,true,'hint');else if(signal==='weak')v3Schedule(p,false,'none');p.attempts=(p.attempts||0)+1;save();render()}catch(e){toast('核對失敗：'+e.message)}}

const v3RemainingBind=bind;
bind=function(){v3RemainingBind();document.querySelector('[data-action="saveAsNote"]')?.addEventListener('click',v3SaveProblemNote);document.querySelector('[data-action="createNote"]')?.addEventListener('click',v3CreateManualNote);document.querySelectorAll('[data-delete-note]').forEach(el=>el.onclick=()=>v3DeleteNote(el.dataset.deleteNote));document.querySelector('[data-action="checkWrittenReview"]')?.addEventListener('click',e=>v3CheckWrittenReview(e.currentTarget.dataset.id))};
render();
