// Whole-sheet scan: one photo can become many individually confirmed wrong questions.
const SHEET_AI_BASE='https://rfpkznuntzxfoeeavwwf.supabase.co/functions/v1/wrongbook-sheet-ai';
state.scanMode=state.scanMode||'single';state.sheetScan=state.sheetScan||null;state.sheetReviewOpen=Boolean(state.sheetReviewOpen);
function v3AnswersEqual(a=[],b=[]){return [...a].map(String).map(x=>x.trim().toUpperCase()).filter(Boolean).sort().join('|')===[...b].map(String).map(x=>x.trim().toUpperCase()).filter(Boolean).sort().join('|')}
function v3SheetDefaultSelected(q){return !v3AnswersEqual(q.recognizedUserAnswer||[],q.correctAnswer||[])}

function captureModal(){return `<div class="modal-backdrop" id="captureModal"><div class="modal v3-capture-modal"><div class="modal-head"><h3>掃描題目</h3><button class="icon-btn" data-action="closeCapture">${icon('close')}</button></div><div class="modal-body"><div class="v3-scan-mode"><button class="${state.scanMode==='single'?'active':''}" data-scan-mode="single">單題</button><button class="${state.scanMode==='sheet'?'active':''}" data-scan-mode="sheet">整張考卷 / 題目頁</button></div><label class="dropzone" for="globalPhotoInput"><strong>📷 拍照或從相簿選圖片</strong><p>${state.scanMode==='sheet'?'可以一次拍整張題目頁。AI 會拆成多題，逐題辨識你的作答與正解，最後由你一次核對。':'AI 會辨識題目、你的作答、正確答案、錯誤敘述與概念。真正存入錯題本前一定要你確認。'}</p></label><img id="capturePreview" class="modal-preview" alt="題目預覽"><div class="callout warn" style="margin-top:12px">${state.scanMode==='sheet'?'整頁模式不會直接存任何題目：拆題後你可以改題幹、學生作答、正解，並取消不想加入的題目。':'多選題例如你寫 AB、正解 ACE：兩個答案會分開顯示，兩個都可改。'}</div><div class="modal-actions"><button class="soft-btn" data-action="loadDemoScan">載入示範</button><button class="primary-btn" data-action="analyzePhoto">${state.scanMode==='sheet'?'AI 拆解整張':'AI 分析這張'}</button></div></div></div></div>`}
function openCapture(){document.body.insertAdjacentHTML('beforeend',captureModal());const input=document.getElementById('globalPhotoInput');input.value='';document.querySelector('#captureModal [data-action="closeCapture"]').onclick=()=>document.getElementById('captureModal')?.remove();document.querySelector('#captureModal [data-action="analyzePhoto"]').onclick=()=>analyzePhoto();document.querySelector('#captureModal [data-action="loadDemoScan"]').onclick=loadDemoScan;document.querySelectorAll('#captureModal [data-scan-mode]').forEach(el=>el.onclick=()=>{state.scanMode=el.dataset.scanMode;save();document.getElementById('captureModal')?.remove();openCapture()});input.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const img=await imageFileToData(f);state.scanImage=img.dataUrl;state.scanBase64=img.base64;state.scanMime=img.mimeType;save();const prev=document.getElementById('capturePreview');if(prev){prev.src=img.dataUrl;prev.style.display='block'}}catch(err){toast('圖片讀取失敗：'+err.message)}}}
async function analyzePhoto(){if(!state.scanBase64)return toast('請先拍照或選一張題目圖片');if(state.scanMode==='sheet')return v3AnalyzeSheet();document.getElementById('captureModal')?.remove();state.aiLoading=true;state.aiError='';render();try{const r=await apiCall('/analyze',{imageBase64:state.scanBase64,mimeType:state.scanMime,syllabus:state.syllabus});state.scan=r.result;state.scanStudent=(r.result.recognizedUserAnswer||[]).map(x=>String(x).toUpperCase());state.scanCorrect=(r.result.correctAnswer||[]).map(x=>String(x).toUpperCase());state.scanConfirmed=false;state.subject=subjectIdFromText(r.result.subject);const id='scan-preview',problem=scanToProblem(id,false);state.problems=state.problems.filter(x=>x.id!=='scan-preview');state.problems.unshift(problem);state.selectedProblemId=id;state.page='notebook';state.annotations=r.result.annotations||[];state.tutor=null;state.aiLoading=false;save();render();toast(`AI 辨識完成：你的作答 ${state.scanStudent.join('')||'未辨識'}，請先確認`)}catch(e){state.aiLoading=false;state.aiError=e.message;save();render();toast('AI 分析失敗：'+e.message)}}
async function v3AnalyzeSheet(){document.getElementById('captureModal')?.remove();state.aiLoading=true;save();render();try{const res=await fetch(SHEET_AI_BASE,{method:'POST',headers:{'content-type':'application/json',apikey:SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify({imageBase64:state.scanBase64,mimeType:state.scanMime})});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(data.detail||data.error||('HTTP '+res.status));const questions=(data.result?.questions||[]).map((q,i)=>({...q,_id:`sheet-${i}-${Date.now().toString(36)}`,_selected:v3SheetDefaultSelected(q),recognizedUserAnswer:(q.recognizedUserAnswer||[]).map(x=>String(x).toUpperCase()),correctAnswer:(q.correctAnswer||[]).map(x=>String(x).toUpperCase())}));state.sheetScan={pageTitle:data.result?.pageTitle||'整張題目',questions};state.sheetReviewOpen=true;state.aiLoading=false;save();render();toast(`已拆出 ${questions.length} 題；請逐題核對後再加入錯題本`)}catch(e){state.aiLoading=false;save();render();toast('整張考卷分析失敗：'+e.message)}}

function v3SheetReviewModal(){const sheet=state.sheetScan;if(!state.sheetReviewOpen||!sheet)return'';const wrong=sheet.questions.filter(q=>q._selected).length;return `<div class="modal-backdrop v3-sheet-backdrop" id="sheetReviewModal"><div class="v3-sheet-modal"><div class="modal-head"><div><h3>${esc(sheet.pageTitle||'整張考卷')}</h3><span class="meta">AI 拆出 ${sheet.questions.length} 題 · 目前選 ${wrong} 題加入</span></div><button class="icon-btn" data-action="closeSheetReview">${icon('close')}</button></div><div class="v3-sheet-tools"><button class="soft-btn" data-action="selectWrongSheet">只選 AI 判斷答錯／未作答</button><button class="soft-btn" data-action="selectAllSheet">全部選取</button><button class="soft-btn" data-action="selectNoneSheet">全部取消</button></div><div class="v3-sheet-list">${sheet.questions.map((q,i)=>v3SheetQuestionCard(q,i)).join('')||'<div class="empty">沒有辨識到題目。建議靠近一點、保持頁面平整後重拍。</div>'}</div><div class="v3-sheet-footer"><span>${wrong} 題會加入錯題本</span><button class="primary-btn" data-action="confirmSheetQuestions">確認並加入選取題目</button></div></div></div>`}
function v3SheetQuestionCard(q,i){const conf=Math.round((q.recognizedAnswerConfidence||0)*100),wrong=!v3AnswersEqual(q.recognizedUserAnswer,q.correctAnswer);return `<article class="v3-sheet-question ${q._selected?'selected':''}"><div class="v3-sheet-check"><input type="checkbox" data-sheet-select="${i}" ${q._selected?'checked':''}><strong>${esc(q.number||String(i+1))}</strong></div><div class="v3-sheet-body"><div class="v3-sheet-meta"><span>${esc(q.subject||'待分類')}</span><span class="${wrong?'v3-wrong':'v3-right'}">${wrong?'AI 判斷需加入':'AI 判斷已答對'}</span><span>作答辨識 ${conf}%</span></div><textarea data-sheet-text="${i}">${esc(q.problemText||'')}</textarea><div class="v3-sheet-answer-grid"><label>辨識到你的作答<input data-sheet-student="${i}" value="${esc((q.recognizedUserAnswer||[]).join(','))}" placeholder="例如 A,B 或 42"></label><label>AI 解出的正解<input data-sheet-correct="${i}" value="${esc((q.correctAnswer||[]).join(','))}" placeholder="例如 A,C,E 或 42"></label></div>${q.recognitionNote?`<div class="meta">${esc(q.recognitionNote)}</div>`:''}<div class="v3-concept-chips">${(q.concepts||[]).map(c=>`<span>${esc(c.nameZh||c.code)}</span>`).join('')}</div></div></article>`}
function v3ParseAnswers(v=''){return String(v).split(/[,，、\s]+/).map(x=>x.trim().toUpperCase()).filter(Boolean)}
function v3ReadSheetEdits(){const qs=state.sheetScan?.questions||[];document.querySelectorAll('[data-sheet-select]').forEach(el=>{const q=qs[Number(el.dataset.sheetSelect)];if(q)q._selected=el.checked});document.querySelectorAll('[data-sheet-text]').forEach(el=>{const q=qs[Number(el.dataset.sheetText)];if(q)q.problemText=el.value.trim()});document.querySelectorAll('[data-sheet-student]').forEach(el=>{const q=qs[Number(el.dataset.sheetStudent)];if(q)q.recognizedUserAnswer=v3ParseAnswers(el.value)});document.querySelectorAll('[data-sheet-correct]').forEach(el=>{const q=qs[Number(el.dataset.sheetCorrect)];if(q)q.correctAnswer=v3ParseAnswers(el.value)})}
async function v3CropDataUrl(dataUrl,crop){if(!dataUrl||!crop)return null;const img=new Image();img.src=dataUrl;await img.decode();const x=clamp(Number(crop.x)||0,0,100)/100*img.naturalWidth,y=clamp(Number(crop.y)||0,0,100)/100*img.naturalHeight,w=clamp(Number(crop.width)||100,1,100)/100*img.naturalWidth,h=clamp(Number(crop.height)||100,1,100)/100*img.naturalHeight,c=document.createElement('canvas');const scale=Math.min(1,1500/Math.max(w,h));c.width=Math.max(1,Math.round(w*scale));c.height=Math.max(1,Math.round(h*scale));c.getContext('2d').drawImage(img,x,y,w,h,0,0,c.width,c.height);const out=c.toDataURL('image/jpeg',.86);return{dataUrl:out,base64:out.split(',')[1],mimeType:'image/jpeg'}}
function v3QuestionToProblem(q,id){const sid=subjectIdFromText(q.subject),concepts=(q.concepts||[]).map(c=>({code:c.code||'',nameZh:c.nameZh||'',chapterHint:c.chapterHint||''})),first=concepts[0]||{},aiCorrections={},aiCorrectionMeta={};for(const c of q.corrections||[]){const l=String(c.label||'').toUpperCase();if(!l)continue;aiCorrections[l]=c.correctedStatement||'';aiCorrectionMeta[l]={whyWrong:c.whyWrong||'',meaningful:c.meaningful!==false,isCorrect:Boolean(c.isCorrect)}}const p={id,subject:sid,title:`${q.number?`第 ${q.number} 題 · `:''}${(q.problemText||'掃描題目').slice(0,24)}`,concept:first.nameZh||q.subject||'待分類概念',conceptCode:first.code||sid.toUpperCase()+'-AI',concepts,chapter:first.chapterHint||subjectById(sid).chapters[0],student:[...(q.recognizedUserAnswer||[])],correct:[...(q.correctAnswer||[])],mastery:30,dueISO:v3DateISO(0),due:'今天',mistakeType:'整張考卷掃描 · 待整理錯因',attempts:1,problemText:q.problemText||'',options:(q.options||[]).map(o=>[String(o.label).toUpperCase(),o.text]),corrections:{},aiCorrections,aiCorrectionMeta,correctionStatus:{},insight:'',aiChapterHint:first.chapterHint||'',questionType:q.questionType||'unknown',confirmed:true,annotations:[],problemKey:''};p.problemKey=v3ProblemKey(p);v3EnsureReview(p);return p}
async function v3ConfirmSheet(){v3ReadSheetEdits();const selected=(state.sheetScan?.questions||[]).filter(q=>q._selected);if(!selected.length)return toast('至少選一題要加入錯題本');const added=[];for(const q of selected){const id=uid('scan'),p=v3QuestionToProblem(q,id);try{const cropped=await v3CropDataUrl(state.scanImage,q.crop);if(cropped){await v3PutImage(id,cropped);p.imageKey=id}}catch{}state.problems.unshift(p);added.push(p)}state.sheetReviewOpen=false;state.sheetScan=null;state.scanImage='';state.scanBase64='';state.scanMode='single';state.selectedProblemId=added[0]?.id||state.selectedProblemId;state.subject=added[0]?.subject||state.subject;state.page='notebook';save();render();toast(`已加入 ${added.length} 題；每題都有自己的原題裁切、作答與正解紀錄`)}

const v3SheetBaseRender=render;
render=function(){v3SheetBaseRender();document.getElementById('sheetReviewModal')?.remove();if(state.sheetReviewOpen&&state.sheetScan)document.body.insertAdjacentHTML('beforeend',v3SheetReviewModal());v3BindSheetModal()};
function v3BindSheetModal(){const modal=document.getElementById('sheetReviewModal');if(!modal)return;modal.querySelector('[data-action="closeSheetReview"]')?.addEventListener('click',()=>{v3ReadSheetEdits();state.sheetReviewOpen=false;save();render()});modal.querySelectorAll('[data-sheet-select]').forEach(el=>el.onchange=()=>{v3ReadSheetEdits();save();render()});modal.querySelector('[data-action="selectWrongSheet"]')?.addEventListener('click',()=>{v3ReadSheetEdits();for(const q of state.sheetScan.questions)q._selected=v3SheetDefaultSelected(q);save();render()});modal.querySelector('[data-action="selectAllSheet"]')?.addEventListener('click',()=>{for(const q of state.sheetScan.questions)q._selected=true;save();render()});modal.querySelector('[data-action="selectNoneSheet"]')?.addEventListener('click',()=>{for(const q of state.sheetScan.questions)q._selected=false;save();render()});modal.querySelector('[data-action="confirmSheetQuestions"]')?.addEventListener('click',v3ConfirmSheet)}
render();
