// Whole-sheet scan: one photo can become many individually confirmed wrong questions.
const SHEET_AI_BASE='https://rfpkznuntzxfoeeavwwf.supabase.co/functions/v1/wrongbook-sheet-ai';
state.scanMode=state.scanMode||'single';state.sheetScan=state.sheetScan||null;state.sheetReviewOpen=Boolean(state.sheetReviewOpen);
function v3AnswersEqual(a=[],b=[]){return [...a].map(String).map(x=>x.trim().toUpperCase()).filter(Boolean).sort().join('|')===[...b].map(String).map(x=>x.trim().toUpperCase()).filter(Boolean).sort().join('|')}
function v3SheetDefaultSelected(q){return !v3AnswersEqual(q.recognizedUserAnswer||[],q.correctAnswer||[])}

function captureModal(){return `<div class="modal-backdrop" id="captureModal"><div class="modal v3-capture-modal"><div class="modal-head"><h3>掃描題目</h3><button class="icon-btn" data-action="closeCapture">${icon('close')}</button></div><div class="modal-body"><div class="v3-scan-mode"><button class="${state.scanMode==='single'?'active':''}" data-scan-mode="single">單題</button><button class="${state.scanMode==='sheet'?'active':''}" data-scan-mode="sheet">整張考卷 / 題目頁</button></div><label class="dropzone" for="globalPhotoInput"><strong>📷 拍照或從相簿選圖片</strong><p>${state.scanMode==='sheet'?'可以一次拍整張題目頁。AI 會拆成多題，逐題辨識你的作答與正解，最後由你一次核對。':'AI 會辨識題目、你的作答、正確答案、錯誤敘述與概念。真正存入錯題本前一定要你確認。'}</p></label><img id="capturePreview" class="modal-preview" alt="題目預覽"><div class="callout warn" style="margin-top:12px">${state.scanMode==='sheet'?'整頁模式不會直接存任何題目：拆題後你可以改題幹、學生作答、正解，並取消不想加入的題目。':'多選題例如你寫 AB、正解 ACE：兩個答案會分開顯示，兩個都可改。'}</div><div class="modal-actions"><button class="soft-btn" data-action="loadDemoScan">載入示範</button><button class="primary-btn" data-action="analyzePhoto">${state.scanMode==='sheet'?'AI 拆解整張':'AI 分析這張'}</button></div></div></div></div>`}
function openCapture(){document.body.insertAdjacentHTML('beforeend',captureModal());const input=document.getElementById('globalPhotoInput');input.value='';document.querySelector('#captureModal [data-action="closeCapture"]').onclick=()=>document.getElementById('captureModal')?.remove();document.querySelector('#captureModal [data-action="analyzePhoto"]').onclick=()=>analyzePhoto();document.querySelector('#captureModal [data-action="loadDemoScan"]').onclick=loadDemoScan;document.querySelectorAll('#captureModal [data-scan-mode]').forEach(el=>el.onclick=()=>{state.scanMode=el.dataset.scanMode;save();document.getElementById('captureModal')?.remove();openCapture()});input.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const img=await imageFileToData(f);state.scanImage=img.dataUrl;state.scanBase64=img.base64;state.scanMime=img.mimeType;save();const prev=document.getElementById('capturePreview');if(prev){prev.src=img.dataUrl;prev.style.display='block'}}catch(err){toast('圖片讀取失敗：'+err.message)}}}
async function analyzePhoto(){if(!state.scanBase64)return toast('請先拍照或選一張題目圖片');if(state.scanMode==='sheet')return v3AnalyzeSheet();document.getElementById('captureModal')?.remove();state.aiLoading=true;state.aiError='';render();try{const r=await apiCall('/analyze',{imageBase64:state.scanBase64,mimeType:state.scanMime,syllabus:state.syllabus});state.scan=r.result;state.scanStudent=(r.result.recognizedUserAnswer||[]).map(x=>String(x).toUpperCase());state.scanCorrect=(r.result.correctAnswer||[]).map(x=>String(x).toUpperCase());state.scanConfirmed=false;state.subject=subjectIdFromText(r.result.subject);const id='scan-preview',problem=scanToProblem(id,false);state.problems=state.problems.filter(x=>x.id!=='scan-preview');state.problems.unshift(problem);state.selectedProblemId=id;state.page='notebook';state.annotations=r.result.annotations||[];state.tutor=null;state.aiLoading=false;save();render();toast(`AI 辨識完成：你的作答 ${state.scanStudent.join('')||'未辨識'}，請先確認`)}catch(e){state.aiLoading=false;state.aiError=e.message;save();render();toast('AI 分析失敗：'+e.message)}}
async function v3AnalyzeSheet(){document.getElementById('captureModal')?.remove();state.aiLoading=true;save();render();try{const res=await fetch(SHEET_AI_BASE,{method:'POST',headers:{'content-type':'application/json',apikey:SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify({imageBase64:state.scanBase64,mimeType:state.scanMime})});const data=await res.json().catch(()=>({error:'invalid_response'}));if(!res.ok)throw new Error(data.detail||data.error||('HTTP '+res.status));const questions=(data.result?.questions||[]).map((q,i)=>({...q,_id:`sheet-${i}-${Date.now().toString(36)}`,_selected:v3SheetDefaultSelected(q),recognizedUserAnswer:(q.recognizedUserAnswer||[]).map(x=>String(x).toUpperCase()),correctAnswer:(q.correctAnswer||[]).map(x=>String(x).toUpperCase())}));state.sheetScan={pageTitle:data.result?.pageTitle||'整張題目',questions};state.sheetReviewOpen=true;state.aiLoading=false;save();render();toast(`已拆出 ${questions.length} 題；請逐題核對後再加入錯題本`)}catch(e){state.aiLoading=false;save();render();toast('整張考卷分析失敗：'+e.message)}}

function v3SheetReviewModal(){const sheet=state.sheetScan;if(!state.sheetReviewOpen||!sheet)return'';const wrong=sheet.questions.filter(q=>q._selected).length;return `<div class="modal-backdrop v3-sheet-backdrop" id="sheetReviewModal"><div class="v3-sheet-modal"><div class="modal-head"><div><h3>${esc(sheet.pageTitle||'整張考卷')}</h3><span class="meta">AI 拆出 ${sheet.questions.length} 題 · 目前選 ${wrong} 題加入</span></div><button class="icon-btn" data-action="closeSheetReview">${icon('close')}</button></div><div class="v3-sheet-tools"><button class="soft-btn" data-action="selectWrongSheet">只選 AI 判斷答錯／未作答</button><button class="soft-btn" data-action="selectAllSheet">全部選取</button><button class="soft-btn" data-action="selectNoneSheet">全部取消</button></div><div class="v3-sheet-list">${sheet.questions.map((q,i)=>v3SheetQuestionCard(q,i)).join('')||'<div class="empty">沒有辨識到題目。建議靠近一點、保持頁面平整後重拍。</div>'}</div><div class="v3-sheet-footer"><span>${wrong} 題會加入錯題本</span><button class="primary-btn" data-action="confirmSheetQuestions">確認並加入選取題目</button></div></div></div>`}
function v3SheetQuestionCard(q,i){const conf=Math.round((q.recognizedAnswerConfidence||0)*100),wrong=!v3AnswersEqual(q.recognizedUserAnswer,q.correctAnswer);return `<article class="v3-sheet-question ${q._selected?'selected':''}"><div class="v3-sheet-check"><input type="checkbox" data-sheet-select="${i}" ${q._selected?'checked':''}><strong>${esc(q.number||String(i+1))}</strong></div><div class="v3-sheet-body"><div class="v3-sheet-meta"><span>${esc(q.subject||'待分類')}</span><span class="${wrong?'v3-wrong':'v3-right'}">${wrong?'AI 判斷需加入':'AI 判斷已答對'}</span><span>作答辨識 ${conf}%</span></div><textarea data-sheet-text="${i}">${esc(q.problemText||'')}</textarea><div class="v3-sheet-answer-grid"><label>辨識到你的作答<input data-sheet-student="${i}" value="${esc((q.recognizedUserAnswer||[]).join(','))}" placeholder="例如 A,B 或 42"></label><label>AI 解出的正解<input data-sheet-correct="${i}" value="${esc((q.correctAnswer||[]).join(','))}" placeholder="例如 A,C,E 或 42"></label></div>${q.recognitionNote?`<div class="meta">${esc(q.recognitionNote)}</div>`:''}<div class="v3-concept-chips">${(q.concepts||[]).map(c=>`<span>${esc(c.nameZh||c.code)}</span>`).join('')}</div></div></article>`}
function v3ParseAnswers(v=''){return String(v).split(/[,，、\s]+/).map(x=>x.trim().toUpperCase()).filter(Boolean)}
function v3ReadSheetEdits(){const qs=state.sheetScan?.questions||[];document.querySelectorAll('[data-sheet-select]').forEach(el=>{const q=qs[Number(el.dataset.sheetSelect)];if(q)q._selected=el.checked});document.querySelectorAll('[data-sheet-text]').forEach(el=>{const q=qs[Number(el.dataset.sheetText)];if(q)q.problemText=el.value.trim()});document.querySelectorAll('[data-sheet-student]').forEach(el=>{const q=qs[Number(el.dataset.sheetStudent)];if(q)q.recognizedUserAnswer=v3ParseAnswers(el.value)});document.querySelectorAll('[data-sheet-correct]').forEach(el=>{const q=qs[Number(el.dataset.sheetCorrect)];if(q)q.correctAnswer=v3ParseAnswers(el.value)})}
async function v3CropDataUrl(dataUrl,crop){if(!dataUrl||!crop)return null;const img=new Image();img.src=dataUrl;await img.decode();const x=clamp(Number(crop.x)||0,0,100)/100*img.naturalWidth,y=clamp(Number(crop.y)||0,0,100)/100*img.naturalHeight,w=clamp(Number(crop.width)||100,1,100)/100*img.naturalWidth,h=clamp(Number(crop.height)||100,1,100)/100*img.naturalHeight,c=document.createElement('canvas');const scale=Math.min(1,1500/Math.max(w,h));c.width=Math.max(1,Math.round(w*scale));c.height=Math.max(1,Math.round(h*scale));c.getContext('2d').drawImage(img,x,y,w,h,0,0,c.width,c.height);const out=c.toDataURL('image/jpeg',.86);return{dataUrl:out,base64:out.split(',')[1],mimeType:'image/jpeg'}}
function v3QuestionToProblem(q,id){const sid=subjectIdFromText(q.subject),concepts=(q.concepts||[]).map(c=>({code:c.code||'',nameZh:c.nameZh||'',chapterHint:c.chapterHint||''})),first=concepts[0]||{},aiCorrections={},aiCorrectionMeta={};for(const c of q.corrections||[]){const l=String(c.label||'').toUpperCase();if(!l)continue;aiCorrections[l]=c.correctedStatement||'';aiCorrectionMeta[l]={whyWrong:c.whyWrong||'',meaningful:c.meaningful!==false,isCorrect:Boolean(c.isCorrect)}}const p={id,subject:sid,title:`${q.number?`第 ${q.number} 題 · `:''}${(q.problemText||'掃描題目').slice(0,24)}`,concept:first.nameZh||q.subject||'待分類概念',conceptCode:first.code||sid.toUpperCase()+'-AI',concepts,chapter:first.chapterHint||subjectById(sid).chapters[0],student:[...(q.recognizedUserAnswer||[])],correct:[...(q.correctAnswer||[])],mastery:30,dueISO:v3DateISO(0),due:'今天',mistakeType:'整張考卷掃描 · 待整理錯因',attempts:1,problemText:q.problemText||'',options:(q.options||[]).map(o=>[String(o.label).toUpperCase(),o.text]),corrections:{},aiCorrections,aiCorrectionMeta,correctionStatus:{},insight:'',aiChapterHint:first.chapterHint||'',questionType:q.questionType||'unknown',confirmed:true,annotations:[],problemKey:''};p.problemKey=v3ProblemKey(p);v3EnsureReview(p);return p}
async function v3ConfirmSheet(){v3ReadSheetEdits();const selected=(state.sheetScan?.questions||[]).filter(q=>q._selected);if(!selected.length)return toast('至少選一題要加入錯題本');const added=[];for(const q of selected){const id=uid('scan'),p=v3QuestionToProblem(q,id);try{const cropped=await v3CropDataUrl(state.scanImage,q.crop);if(cropped){await v3PutImage(id,cropped);p.imageKey=id}}catch{}state.problems.unshift(p);added.push(p)}state.sheetReviewOpen=false;state.sheetScan=null;state.scanImage='';state.scanBase64='';state.scanMode='single';state.selectedProblemId=added[0]?.id||state.selectedProblemId;state.subject=added[0]?.subject||state.subject;state.page='notebook';save();render();toast(`已加入 ${added.length} 題；每題都有自己的原題裁切、作答與正解紀錄`)}

const v3SheetBaseRender=render;
render=function(){v3SheetBaseRender();document.getElementById('sheetReviewModal')?.remove();if(state.sheetReviewOpen&&state.sheetScan)document.body.insertAdjacentHTML('beforeend',v3SheetReviewModal());v3BindSheetModal()};
function v3BindSheetModal(){const modal=document.getElementById('sheetReviewModal');if(!modal)return;modal.querySelector('[data-action="closeSheetReview"]')?.addEventListener('click',()=>{v3ReadSheetEdits();state.sheetReviewOpen=false;save();render()});modal.querySelectorAll('[data-sheet-select]').forEach(el=>el.onchange=()=>{v3ReadSheetEdits();save();render()});modal.querySelector('[data-action="selectWrongSheet"]')?.addEventListener('click',()=>{v3ReadSheetEdits();for(const q of state.sheetScan.questions)q._selected=v3SheetDefaultSelected(q);save();render()});modal.querySelector('[data-action="selectAllSheet"]')?.addEventListener('click',()=>{for(const q of state.sheetScan.questions)q._selected=true;save();render()});modal.querySelector('[data-action="selectNoneSheet"]')?.addEventListener('click',()=>{for(const q of state.sheetScan.questions)q._selected=false;save();render()});modal.querySelector('[data-action="confirmSheetQuestions"]')?.addEventListener('click',v3ConfirmSheet)}
render();

// v4 single-question capture: the student explicitly outlines the wanted problem before OCR.
// This prevents neighbouring questions/handwriting from contaminating recognition and keeps the selected diagram source intact.
state.scanSelection=state.scanSelection||null;
const v4ProblemSelectStyle=document.createElement('style');
v4ProblemSelectStyle.textContent=`
.v4-select-help{margin:12px 0 8px;padding:10px 12px;border:1px solid #e5e2ff;background:#f7f5ff;border-radius:12px;color:#4e476f;font-size:13px;line-height:1.45}.v4-select-help strong{display:block;color:#2f2a45;margin-bottom:2px}.v4-select-stage{position:relative;width:100%;margin-top:10px;border-radius:14px;overflow:hidden;background:#ececf1;touch-action:none}.v4-select-stage .modal-preview{display:block!important;width:100%;height:auto;max-height:58vh;object-fit:contain;margin:0}.v4-select-canvas{position:absolute;inset:0;width:100%;height:100%;touch-action:none;cursor:crosshair}.v4-select-pill{position:absolute;left:10px;top:10px;z-index:2;padding:6px 9px;border-radius:999px;background:rgba(22,22,30,.76);color:#fff;font-size:12px;font-weight:800;pointer-events:none}.v4-select-tools{display:flex;gap:8px;align-items:center;justify-content:space-between;margin-top:8px}.v4-select-status{font-size:12px;color:#787483}.v4-select-status.ready{color:#3d7454;font-weight:800}.v4-select-reset{border:1px solid #dedde6;background:#fff;border-radius:10px;padding:7px 10px;font:inherit;font-size:12px;font-weight:800;color:#595565}.v4-select-needed{box-shadow:0 0 0 3px rgba(109,93,252,.10)}@media(max-width:700px){.v4-select-help{font-size:12.5px}.v4-select-stage .modal-preview{max-height:52vh}.v4-select-pill{font-size:11px}}
`;
document.head.appendChild(v4ProblemSelectStyle);

function v4PointFromEvent(e,rect){return{x:Math.max(0,Math.min(1,(e.clientX-rect.left)/Math.max(1,rect.width))),y:Math.max(0,Math.min(1,(e.clientY-rect.top)/Math.max(1,rect.height)))}}
function v4DrawSelection(canvas,points=[]){const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);if(points.length<2)return;ctx.beginPath();ctx.moveTo(points[0].x*rect.width,points[0].y*rect.height);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x*rect.width,points[i].y*rect.height);if(points.length>3)ctx.closePath();ctx.fillStyle='rgba(109,93,252,.10)';ctx.fill();ctx.lineWidth=4;ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle='rgba(109,93,252,.96)';ctx.stroke()}
function v4SetSelectionStatus(stage){const status=stage?.parentElement?.querySelector('.v4-select-status'),ready=(state.scanSelection?.points||[]).length>=4;if(status){status.textContent=ready?'已圈選：只會辨識這個範圍':'尚未圈選題目';status.classList.toggle('ready',ready)}stage?.classList.toggle('v4-select-needed',!ready)}
function v4ResetSelection(stage,canvas){state.scanSelection=null;v4DrawSelection(canvas,[]);v4SetSelectionStatus(stage);save()}
function v4InstallProblemSelector(){if(state.scanMode!=='single')return;const modal=document.getElementById('captureModal'),input=document.getElementById('globalPhotoInput'),preview=document.getElementById('capturePreview');if(!modal||!input||!preview||modal.dataset.v4ProblemSelector==='1')return;modal.dataset.v4ProblemSelector='1';state.scanSelection=null;
  const drop=modal.querySelector('.dropzone p');if(drop)drop.textContent='先拍整頁也沒關係。下一步請用手指沿著你要加入錯題本的「那一題」外圍圈一圈。';
  const help=document.createElement('div');help.className='v4-select-help';help.innerHTML='<strong>① 先圈出你要的題目</strong>只把圈內送給 AI。文字會重建成可編輯題目；若題目含圖表、幾何圖或題目圖片，會保留圈選範圍的原圖，避免 AI 猜錯圖。';preview.before(help);
  const stage=document.createElement('div');stage.className='v4-select-stage';stage.style.display='none';preview.before(stage);stage.appendChild(preview);const pill=document.createElement('div');pill.className='v4-select-pill';pill.textContent='用手指沿題目外圍圈選';stage.appendChild(pill);const canvas=document.createElement('canvas');canvas.className='v4-select-canvas';stage.appendChild(canvas);
  const tools=document.createElement('div');tools.className='v4-select-tools';tools.innerHTML='<span class="v4-select-status">尚未圈選題目</span><button type="button" class="v4-select-reset">重新圈選</button>';stage.after(tools);tools.querySelector('.v4-select-reset').onclick=()=>v4ResetSelection(stage,canvas);
  let drawing=false,points=[];canvas.addEventListener('pointerdown',e=>{if(!preview.src)return;drawing=true;points=[];canvas.setPointerCapture?.(e.pointerId);points.push(v4PointFromEvent(e,canvas.getBoundingClientRect()));v4DrawSelection(canvas,points);e.preventDefault()});canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=v4PointFromEvent(e,canvas.getBoundingClientRect()),last=points[points.length-1];if(!last||Math.hypot(p.x-last.x,p.y-last.y)>.004){points.push(p);v4DrawSelection(canvas,points)}e.preventDefault()});const finish=e=>{if(!drawing)return;drawing=false;canvas.releasePointerCapture?.(e.pointerId);if(points.length<4){v4ResetSelection(stage,canvas);toast('請沿著整題外圍圈一圈');return}state.scanSelection={points:points.map(p=>({x:Number(p.x.toFixed(5)),y:Number(p.y.toFixed(5))}))};v4DrawSelection(canvas,state.scanSelection.points);v4SetSelectionStatus(stage);save();e.preventDefault()};canvas.addEventListener('pointerup',finish);canvas.addEventListener('pointercancel',()=>{drawing=false});
  const baseChange=input.onchange;input.onchange=async e=>{state.scanSelection=null;await baseChange?.(e);if(!state.scanImage)return;state.scanSourceImage=state.scanImage;state.scanSourceBase64=state.scanBase64;state.scanSourceMime=state.scanMime;stage.style.display='block';tools.style.display='flex';try{await preview.decode()}catch{}requestAnimationFrame(()=>{v4DrawSelection(canvas,[]);v4SetSelectionStatus(stage)});save()};
  const analyze=modal.querySelector('[data-action="analyzePhoto"]');if(analyze)analyze.textContent='辨識這一題';tools.style.display='none';
}

async function v4CropOutlinedProblem(){const selection=state.scanSelection,source=state.scanSourceImage||state.scanImage;if(!source||!(selection?.points?.length>=4))return null;const img=new Image();img.src=source;await img.decode();const pts=selection.points;let minX=Math.min(...pts.map(p=>p.x)),maxX=Math.max(...pts.map(p=>p.x)),minY=Math.min(...pts.map(p=>p.y)),maxY=Math.max(...pts.map(p=>p.y));const pad=.018;minX=Math.max(0,minX-pad);minY=Math.max(0,minY-pad);maxX=Math.min(1,maxX+pad);maxY=Math.min(1,maxY+pad);const sx=minX*img.naturalWidth,sy=minY*img.naturalHeight,sw=Math.max(1,(maxX-minX)*img.naturalWidth),sh=Math.max(1,(maxY-minY)*img.naturalHeight),scale=Math.min(1,1800/Math.max(sw,sh)),out=document.createElement('canvas');out.width=Math.max(1,Math.round(sw*scale));out.height=Math.max(1,Math.round(sh*scale));const ctx=out.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,out.width,out.height);ctx.save();ctx.beginPath();pts.forEach((p,i)=>{const x=((p.x-minX)/(maxX-minX))*out.width,y=((p.y-minY)/(maxY-minY))*out.height;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.clip();ctx.drawImage(img,sx,sy,sw,sh,0,0,out.width,out.height);ctx.restore();const dataUrl=out.toDataURL('image/jpeg',.92);return{dataUrl,base64:dataUrl.split(',')[1],mimeType:'image/jpeg',bbox:{x:minX,y:minY,width:maxX-minX,height:maxY-minY}}}

const v4BaseOpenCapture=openCapture;
openCapture=function(){v4BaseOpenCapture();v4InstallProblemSelector()};
const v4BaseAnalyzePhoto=analyzePhoto;
analyzePhoto=async function(){if(state.scanMode!=='single')return v4BaseAnalyzePhoto();if(!state.scanBase64)return toast('請先拍照或選一張題目圖片');if(!(state.scanSelection?.points?.length>=4)){document.querySelector('.v4-select-stage')?.classList.add('v4-select-needed');return toast('請先用手指圈出你要辨識的那一題')}try{const cropped=await v4CropOutlinedProblem();if(!cropped)throw new Error('selection_crop_failed');state.scanImage=cropped.dataUrl;state.scanBase64=cropped.base64;state.scanMime=cropped.mimeType;state.scanSelection.bbox=cropped.bbox;save();return await v4BaseAnalyzePhoto()}catch(e){toast('圈選區域處理失敗，請重新圈選');console.warn('[wrongbook] problem selection crop failed',e)}};
