// Verified publisher mappings. This only reads rows marked verified=true by RLS.
const v3MappingCache=new Map();
function v3MappingKey(p){return `${state.syllabus.level||'高中'}|${p.subject}|${p.conceptCode||''}|${activePublisher(p.subject)}`}
function v3FormatMapping(m){if(!m)return'';return [m.book_title,m.volume,m.chapter,m.section,m.page_start?`p.${m.page_start}${m.page_end&&m.page_end!==m.page_start?'–'+m.page_end:''}`:''].filter(Boolean).join(' · ')}
async function v3FetchVerifiedMapping(p){if(!p?.conceptCode)return null;const key=v3MappingKey(p);if(v3MappingCache.has(key))return v3MappingCache.get(key);const qs=new URLSearchParams({select:'book_title,volume,chapter,section,page_start,page_end,edition,source_note',level:`eq.${state.syllabus.level||'高中'}`,subject:`eq.${p.subject}`,concept_code:`eq.${p.conceptCode}`,publisher:`eq.${activePublisher(p.subject)}`,verified:'eq.true',limit:'1'});try{const r=await fetch(`${V3_SB_URL}/rest/v1/wb_textbook_mappings?${qs}`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY}});if(!r.ok)throw new Error('HTTP '+r.status);const rows=await r.json(),m=rows?.[0]||null;v3MappingCache.set(key,m);if(m){p.verifiedBookLocation=v3FormatMapping(m);p.verifiedBookSource=m.source_note||'';v3CloudSuppress=true;try{v3CloudBaseSave()}finally{v3CloudSuppress=false}render()}return m}catch{return null}}

function mappingPanel(p){
  const publisher=activePublisher(p.subject),verified=p.verifiedBookLocation||'',personal=p.bookLocation||'',suggested=p.aiChapterHint||'';
  return `<section class="panel"><div class="panel-head"><h3>概念 → 你的課本位置</h3><button class="text-btn" data-action="editBookLocation">${verified?'補充我的位置':'設定位置'}</button></div><div class="mapping"><span class="concept-code">${esc(p.conceptCode||'CONCEPT')}</span><div class="concept-name">${esc(p.concept)}</div><div class="meta">${subjectById(p.subject).name} · 108 課綱概念層</div><div class="mapping-row"><span class="publisher">你使用</span><span><strong>${esc(publisher)}</strong></span></div><div class="mapping-row"><span class="publisher">已驗證</span><span>${verified?`<strong>${esc(verified)}</strong><small class="v3-verified">✓ verified</small>`:`<span class="mapping-unknown">目前資料庫還沒有這個版本的已驗證對照</span>`}</span></div>${personal?`<div class="mapping-row"><span class="publisher">你設定</span><span><strong>${esc(personal)}</strong></span></div>`:''}${suggested&&!verified?`<div class="mapping-row"><span class="publisher">AI 建議</span><span>${esc(suggested)}</span></div>`:''}<div class="callout" style="margin-top:10px">只有資料庫中 verified=true 的出版社對照才會標成「已驗證」；AI 建議永遠不會冒充正式章號。</div></div></section>`;
}

const v3MappingRender=render;
render=function(){v3MappingRender();const p=selectedProblem();if(['notebook','tutor'].includes(state.page)&&p&&!p.verifiedBookLocation)setTimeout(()=>v3FetchVerifiedMapping(p),0)};
render();
